UPDATE public.routines_bank SET description = '<p>Your body is doing something remarkable right now. And it deserves your full support.</p>
<p>Most women spend their period pushing through. Ibuprofen, coffee, and willpower. Life doesn''t stop so they don''t stop either. And while that resilience is real, there''s a cost to it. When you fight your body instead of working with it, everything gets harder. The pain feels worse. The exhaustion goes deeper. And you end the week more depleted than you needed to be. This routine is a different approach.</p>
<h3>What this routine is for</h3>
<p>The Period Care Routine is designed for the days when your body is going through its monthly cycle. It''s not about doing less — it''s about doing the right things. Small, intentional acts that support what your body actually needs right now: warmth, hydration, rest, and a little extra kindness toward yourself. Research shows that stress and physical tension worsen period symptoms. When you soften — physically and emotionally — your body responds. Cramps ease. Mood stabilizes. Energy is preserved for what actually matters.</p>
<h3>What you''ll do</h3>
<p>Six gentle daily tasks, about fifteen minutes total. You''ll start with three deep breaths — a simple nervous system reset that signals your body it''s safe to relax. Then a quick body scan to notice where you''re holding tension and gently release it. Staying hydrated throughout the day helps reduce bloating and fatigue more than most women realize — water actually lowers the concentration of prostaglandins, the chemicals directly linked to cramping. Giving yourself permission to rest — actually saying it, not just thinking it — is one of the most powerful things you can do on a hard day. A warm cup of chamomile tea in the evening soothes cramps and eases your body toward sleep. And ending the day with one thing you''re grateful for anchors you in something good when everything else feels heavy.</p>
<h3>Why it works</h3>
<p>Every task was chosen because it directly supports what your body needs during menstruation. Chamomile has real antispasmodic properties that reduce uterine cramping. Deep breathing activates the parasympathetic nervous system, reducing the fight-or-flight response that amplifies pain. Hydration works at a chemical level. This is self-care backed by biology.</p>
<h3>A note from Razie</h3>
<p>I used to white-knuckle through every period. I told myself I didn''t have time to slow down. What I know now is that slowing down for five days actually gave me more — more energy in the weeks that followed, more patience, more of myself. Your body is not working against you this week. It''s just asking for a little more than usual. Give it that. You''ll be surprised what it gives back.</p>
<p><em>5 days · ~15 minutes/day · Best time: Morning and Evening</em></p>' WHERE id = '5fa32332-14f5-4860-a615-22349cbb8542';

UPDATE public.routines_bank SET description = '<p>Nobody tells you about the guilt.</p>
<p>They tell you about the sleepless nights. The feeding schedules. The way your whole life reorganizes itself around this tiny person. But nobody really prepares you for that specific feeling — the one that shows up the moment you try to do something just for yourself. The whisper that says you should be with the baby. You should be sleeping when the baby sleeps. You should be more grateful. You should be doing more. That guilt is lying to you.</p>
<p>Taking care of yourself right now is not selfish. It is the most practical thing you can do for your baby, your partner, and every person who depends on you. You cannot give from empty. And right now, you are being asked to give more than you ever have before. This routine exists to remind you that you matter too.</p>
<h3>Keep it simple</h3>
<p>This is the shortest routine in Rilo. Five tasks. Ten minutes. That''s it. Because right now, ten minutes is everything. Ten minutes is the shower you keep postponing. The glass of water you forgot to drink. The breath you haven''t taken since 3am. There is no pressure here. No gold star for doing it perfectly. Just five small acts that say — I am still here.</p>
<h3>What you''ll do</h3>
<p>Wash your face. Not because you need to look a certain way — because that sixty seconds of warm water and intentional care is a message you send yourself. A signal that the woman who existed before the baby is still there. Keep a water bottle with you all day. New moms are chronically dehydrated and most don''t realize it. Dehydration makes exhaustion worse, mood more fragile, and breast milk supply lower if you''re nursing. Step outside once. Even for two minutes. Natural light resets your circadian rhythm and tells your brain it''s daytime — which matters enormously when your sleep is broken into fragments. Say one kind thing to yourself as if you were a friend. You would never speak to a friend the way you speak to yourself at 2am when the baby won''t stop crying. Tell yourself the same thing you''d tell her. And before you sleep — however that sleep comes tonight — a simple breathing exercise. In for four, out for six. It activates your parasympathetic nervous system and makes whatever sleep you get more restorative.</p>
<h3>Why 21 days</h3>
<p>Twenty-one days of a repeated behavior begins to build genuine neural pathways. It starts to feel automatic. After twenty-one days you won''t have to remind yourself to drink water or step outside. It will just be part of who you are now. The woman who takes care of herself even in the hardest season of her life. That woman is already you. This routine just helps her show up.</p>
<h3>A note from Razie</h3>
<p>I became a mother while building Rilo. I know this exhaustion from the inside. There were weeks where I felt like I had completely disappeared into motherhood — like I existed only as a function, not a person. And the thing that brought me back, every time, was the smallest act of showing up for myself. Just one thing. Just today. You are not just a mom. You are a whole woman who happens to also be a mom. Don''t let one — as beautiful and important as it is — erase the other. You matter. Still. Always.</p>
<p><em>21 days · ~10 minutes/day · Best time: Any time you can steal</em></p>' WHERE id = '7fac584c-8d17-4eb7-9f4a-b2ce038ff807';

UPDATE public.routines_bank SET description = '<p>Something ended. And it hurts in a way that''s hard to explain to people who aren''t inside it with you.</p>
<p>Maybe it was your choice. Maybe it wasn''t. Maybe it was mutual and still feels like the ground shifted under you. Grief doesn''t follow logic. It doesn''t care how prepared you were or how right the decision was. It just shows up and sits in your chest and makes the smallest things — a song, a restaurant, a time of day — feel like something sharp. You don''t need to be fixed right now. You don''t need to rush through this on anyone else''s timeline. What you need is to come back to yourself. One day at a time. One small act at a time. That''s what this routine is for.</p>
<h3>The hardest part nobody talks about</h3>
<p>Breakups don''t just end a relationship. They end a version of yourself — the one that existed inside that relationship. Grief after a breakup is real grief. Your brain processes it the same way it processes any significant loss. Neuroimaging studies show that romantic rejection activates the same neural pathways as physical pain. You are not being dramatic. You are not weak. You are human, and you are hurting, and that is allowed.</p>
<h3>What this routine does</h3>
<p>Seven tasks. Twenty minutes. Designed to do one thing above everything else — remind you that you still exist. That there is a whole woman here who is not defined by what just ended.</p>
<p>You''ll smile at yourself in the mirror. Not because you feel like smiling — because the physical act of it releases serotonin regardless of your mood. You''ll walk for five minutes. Movement processes grief through the body in a way stillness cannot. You''ll allow yourself to feel without judgment. To cry, to be angry, to feel nothing. All of it is allowed here. You''ll name one person who cares about you. Right now your brain is telling you that you are alone. It''s lying. You''ll write down your thoughts — the what ifs, the replays, the things you wish you''d said. What lives in writing stops living rent-free in your nervous system. You''ll say one kind thing to yourself. The hardest task in the whole routine. And you''ll thank yourself for making it through the day.</p>
<h3>Do this for seven days</h3>
<p>Not because you''ll be healed in seven days. You won''t be, and that''s okay. But seven days of showing up for yourself builds something. A quiet proof that you can get through this. The relationship ended. You didn''t.</p>
<h3>A note from Razie</h3>
<p>Heartbreak is one of the most disorienting human experiences there is. It makes you question things about yourself that have nothing to do with what actually happened. Whatever story you''re telling yourself right now about your worth, your lovability, your future — please hold it loosely. It was written by grief, not by truth. The truth is that you are whole. You were whole before. You are whole now. Come back to these seven tasks every day this week. I''ll be here.</p>
<p><em>7 days · ~20 minutes/day · Best time: Morning</em></p>' WHERE id = '0093efba-271d-41fc-8e85-9ca7048f94b4';

UPDATE public.routines_bank SET description = '<p>Your brain doesn''t work against you. It just works differently. And most routines were not built for the way you think. This one was.</p>
<p>The ADHD Routine isn''t about doing more. It''s about removing the friction that makes starting feel impossible. Because the hardest part isn''t the work itself — it''s the gap between intention and action. This routine closes that gap with six simple tasks that take about fifteen minutes.</p>
<h3>What you''ll do</h3>
<p>You''ll begin with three deep breaths to settle the noise and signal your brain that it''s time to focus. Then you''ll plan your top three priorities — not everything, just three. Trying to hold a full to-do list in an ADHD brain is like trying to carry water in your hands. Three things fit. You''ll break your biggest task into smaller steps, because a task without a clear first action is a task that doesn''t get started. Turn off notifications for one hour — not forever, just one hour. Remove the interruptions that hijack your attention before you''ve even built momentum. Use a focus timer for deep work, because time-boxing is one of the most effective tools for ADHD brains. And at the end of the day, name one thing you accomplished — because ADHD brains tend to remember only what went wrong, never what went right.</p>
<h3>Do this for 14 days</h3>
<p>Not because you''ll be fixed — you don''t need fixing. But because two weeks of this structure builds something your brain can start to rely on. Consistency creates its own momentum.</p>
<h3>A note from Razie</h3>
<p>The women I''ve worked with who have ADHD are some of the most creative, passionate, deeply feeling people I know. The same brain that makes focus hard also makes you extraordinary in ways most people aren''t. This routine doesn''t dim that. It just gives it a little structure to work from.</p>
<p><em>14 days · ~15 minutes/day · Best time: Morning</em></p>' WHERE id = '6e2b8900-a8cf-4e8e-9795-fb5b15f3d525';

UPDATE public.routines_bank SET description = '<p>Anxiety doesn''t always arrive dramatically. Sometimes it''s just a hum. A tightness behind the eyes. A restlessness that follows you from room to room without a name or a reason. You don''t need to know why it''s there to do something about it.</p>
<p>This routine works directly with your nervous system — not around it. Every task was chosen because it has a measurable effect on the physiological state that anxiety creates in your body. When your nervous system calms, everything else follows. The thoughts slow down. The chest loosens. The day becomes manageable again.</p>
<h3>What you''ll do</h3>
<p>Six tasks. Fifteen minutes. Three deep breaths signal your parasympathetic nervous system to take over from the stress response — your exhale is longer than your inhale, which is the key. A body scan brings you out of your head and into your body, where anxiety has less power. A mindful breathing exercise deepens that shift. A short walk without distraction moves the stress hormones through your body physically — cortisol needs movement to metabolize. Visualizing a peaceful place activates the same neural pathways as actually being there. And one kind word to yourself — because anxiety and self-compassion cannot fully coexist. One quiets the other.</p>
<h3>Start with 3 days</h3>
<p>Just three. That''s all this asks. If after three days you need more — start again.</p>
<h3>A note from Razie</h3>
<p>Anxiety is not a weakness. It''s what happens when a caring, responsible woman carries more than her nervous system was designed to hold alone. You don''t have to think your way out of it. Sometimes you just have to breathe your way back.</p>
<p><em>3 days · ~15 minutes/day · Best time: Whenever anxiety rises</em></p>' WHERE id = '4b630618-cd34-47f9-bbd7-15f4addf88a2';

UPDATE public.routines_bank SET description = '<p>You''re not lazy. You never were.</p>
<p>Procrastination is almost never about laziness. It''s about overwhelm. About a task that feels too big or too unclear or too loaded with the possibility of failure. So your brain does what brains do — it avoids the discomfort and finds something easier to do instead. The problem isn''t your work ethic. It''s the gap between intention and starting. This routine closes that gap.</p>
<h3>What you''ll do</h3>
<p>Five tasks. Ten minutes. All of them designed to remove the friction that stands between you and beginning. Writing your goals in the morning gives your brain a clear destination before the day fills with noise. Writing down the very first step of your task removes the vagueness that makes starting feel impossible — you can''t start "the project" but you can start "open the document." Starting with your most important task first uses your freshest mental energy on what matters most. A focus timer creates a container — you''re not working forever, you''re working for this specific block of time. And checking one thing off your list gives your brain the dopamine hit it''s been looking for all along. One thing done. That''s the whole strategy.</p>
<h3>Do this for 14 days</h3>
<p>Because procrastination is a habit. And the only thing that breaks a habit is a stronger one built in its place.</p>
<h3>A note from Razie</h3>
<p>The women I know who struggle with procrastination are almost always the ones with the highest standards. They''re not avoiding the work — they''re afraid of doing it imperfectly. Done imperfectly is infinitely better than not done at all. Start today. Right now, after you close this.</p>
<p><em>14 days · ~10 minutes/day · Best time: First thing in the morning</em></p>' WHERE id = 'a2312926-8075-4f93-acc8-df17aad63557';

UPDATE public.routines_bank SET description = '<p>6:47am. The baby is crying. Your phone has three unread work messages. Breakfast isn''t made. You haven''t brushed your teeth yet. And somewhere in the back of your mind a voice says — how is it already this hard and the day hasn''t even started? That morning. You know that morning.</p>
<p>A 20-year Harvard study tracking thousands of working parents found that the ones who maintained even the smallest daily self-care practices reported significantly higher energy, better emotional regulation, and stronger relationships — not despite their busy lives, but because of what those small practices did to their nervous systems every single day. Small things. Done consistently. Change everything.</p>
<h3>What you''ll do</h3>
<p>Seven tasks built specifically around the rhythm of a working parent''s day. Morning sunlight — even ten minutes — resets your circadian clock and boosts daytime alertness, which matters when your sleep is interrupted and fragmented. Keeping a water bottle filled addresses the chronic dehydration that most parents don''t realize is quietly making their exhaustion worse. Eating one meal without your phone gives your brain an actual break — something it almost never gets.</p>
<p>Then there''s the family time task. Research from the University of Michigan found that the quality of time with children matters far more than the quantity. Twenty minutes of genuinely present, phone-down connection does more for your child''s development — and your relationship — than hours of distracted proximity. Put the phone down. Really be there.</p>
<p>Writing tomorrow''s goals before bed takes the mental load out of your head and onto the page, so your brain can actually rest instead of running through the list all night. And a consistent bedtime — even thirty minutes more consistent than what you have now — measurably improves the quality of every hour of sleep you get.</p>
<h3>21 days</h3>
<p>Not because that''s when everything gets easier. Because that''s when this stops feeling like effort and starts feeling like just what you do.</p>
<h3>A note from Razie</h3>
<p>You are doing one of the hardest things a person can do. Building a career and raising a family simultaneously, with never quite enough hours and always quite enough guilt. This routine won''t give you more time. But it will make you feel more like yourself inside the time you have. And that woman — the one who feels like herself — she''s a better parent, a better professional, and a better everything. She''s already you. She just needs five minutes.</p>
<p><em>21 days · ~20 minutes/day · Best time: Morning and Evening</em></p>' WHERE id = '4452fd59-ed3e-4ebd-a2e9-1a9056ee3e58';

UPDATE public.routines_bank SET description = '<p>You made it through.</p>
<p>That might not feel like enough right now. But it is. Getting through a hard day when everything in you wanted to stop — that is not nothing. That is actually everything. Now put it down.</p>
<p>Not analyze it. Not replay it. Not draft the email you wish you''d sent or rehearse the conversation you''re going to have tomorrow. Just — put it down. For tonight. It will still be there in the morning if you need it. But right now your only job is to transition out of the day and back into yourself. That''s what this routine does.</p>
<h3>What you''ll do</h3>
<p>Six tasks. Twenty minutes. Starting with your space — because external order creates internal calm, and five minutes of tidying tells your nervous system the day is wrapping up. Then dimming the lights, because bright light suppresses melatonin and keeps your brain in daytime mode long after your body wants to rest. Writing down two things that are weighing on you — not to solve them, just to move them from inside your head to outside it. A sleep breathing exercise that activates your parasympathetic nervous system and prepares your body for genuine recovery. One kind word to yourself before you close your eyes. And one thing — just one — that you''re grateful for.</p>
<p>Gratitude before sleep isn''t spiritual bypassing. It''s neuroscience. Studies from UC Davis show it measurably increases sleep quality and reduces the time it takes to fall asleep. End the day with something good. Your brain will carry it into sleep.</p>
<h3>Three days</h3>
<p>That''s all. Just tonight, tomorrow night, and the night after.</p>
<h3>A note from Razie</h3>
<p>Hard days are not signs that something is wrong with your life. They''re signs that you''re in it. Fully. That you care about what you''re building. Rest tonight. Tomorrow is a different day.</p>
<p><em>3 days · ~20 minutes/day · Best time: Evening</em></p>' WHERE id = 'e7554088-25d2-4f82-a21c-2baf2d424797';

UPDATE public.routines_bank SET description = '<p>When did you last feel truly seen by someone? Not liked. Not needed. Not appreciated for what you do. Seen — for who you actually are underneath all of it. If that answer took a while to come, this routine is for you.</p>
<p>Loneliness is one of the most misunderstood experiences in modern life. Because it has almost nothing to do with how many people are around you. You can be surrounded — by family, by colleagues, by a full and busy life — and still feel that specific ache of not being truly known. And it is not just emotional. A landmark study from Brigham Young University analyzing data from over 3 million people found that chronic loneliness increases the risk of early death by 26%. It affects your immune system, your sleep, your cognitive function. Loneliness is a health issue. And connection — even small daily acts of it — is medicine.</p>
<h3>What you''ll do</h3>
<p>Five tasks. All of them small. All of them pointed in one direction — outward. Name one person who cares about you. Not to do anything with it yet — just to let it be true. To feel the reality of being loved even for a moment. Send a kind message to someone. Check in on someone you''ve been meaning to reach out to. Express gratitude to a loved one — specifically, not generically. And end the day with a hug if you can. Physical touch releases oxytocin, the bonding hormone, which directly counteracts the physiological effects of loneliness.</p>
<p>Here is the counterintuitive truth this routine is built on. The antidote to feeling unseen is not waiting to be noticed. It is choosing to notice someone else first. Connection flows both ways — and you get to start it.</p>
<h3>Seven days</h3>
<p>One week of reaching out instead of waiting. You will be surprised what comes back.</p>
<h3>A note from Razie</h3>
<p>I have felt this loneliness. In the middle of a full life, surrounded by people who loved me, I have felt completely invisible. What brought me back every time was one small act of genuine connection. One message. One conversation. One moment of being real with someone. You are not as alone as the feeling says you are. Reach out today. Even just once.</p>
<p><em>7 days · ~15 minutes/day · Best time: Any time of day</em></p>' WHERE id = 'f186e456-f41b-45f3-9242-97c0e1ec00a1';

UPDATE public.routines_bank SET description = '<p>Pressure is not the enemy. How you carry it is.</p>
<p>The most successful women don''t avoid high-pressure situations. They build the capacity to move through them without losing themselves in the process. That capacity is not a personality trait you either have or don''t. It is a set of daily practices. Repeatable. Learnable. Buildable. That''s what this routine is.</p>
<p>Stanford psychologist Kelly McGonigal spent years studying stress and found something that changed how scientists think about it entirely. Stress is only harmful when you believe it is harmful. When you view pressure as a signal that something important is happening — that your body is mobilizing resources to help you rise to the challenge — the same physiological response that causes burnout becomes fuel. This routine is built on that principle. Not to eliminate the pressure. To help you carry it better.</p>
<h3>What you''ll do</h3>
<p>Seven tasks. Twenty minutes. Designed for the woman who is building something real and needs to stay grounded while she does it. Planning your top three priorities every morning stops the scattered energy that makes high-pressure days feel chaotic. Turning off notifications for one hour creates a window of genuine deep work — the kind that actually moves things forward rather than just keeping you busy. Three deep breaths before a hard task or difficult meeting lowers cortisol measurably within ninety seconds. A five-minute walk metabolizes stress hormones physically — your body needs movement to process what your mind is carrying. Eating one real meal without your phone gives your prefrontal cortex — the part responsible for decision-making and emotional regulation — the glucose it needs to function at its best under pressure. Telling yourself "I just need to do my best" interrupts the perfectionism spiral before it starts. And naming one accomplishment at the end of the day retrains your brain to register progress, not just problems.</p>
<h3>14 days</h3>
<p>Two weeks to build a stress response that works for you instead of against you.</p>
<h3>A note from Razie</h3>
<p>I have built things under enormous pressure. I know what it feels like when the stakes are high and the margin for error feels small and your nervous system is running at full capacity just to keep up. The women who make it through those seasons aren''t the ones who feel no stress. They''re the ones who take care of themselves well enough to keep going. You are building something. Stay grounded. Keep going.</p>
<p><em>14 days · ~20 minutes/day · Best time: Morning</em></p>' WHERE id = 'c4bcec41-4f4b-4e45-81b2-3b526139bdfe';