
-- Rolex Story
INSERT INTO reading_content (id, title, subtitle, description, emoji, type, category, author, reading_time_minutes, theme_color, is_published, is_premium, sort_order)
VALUES (
  'd3e4f5a6-b7c8-9012-defa-234567890123',
  'Hans Wilsdorf: The Rolex Story',
  'From Orphan to Luxury Icon',
  'The inspiring story of Hans Wilsdorf — an orphan boy from a small German town who lost both parents by age 12, yet went on to create Rolex, the world''s most iconic luxury watch brand. A tale of resilience, innovation, and relentless pursuit of perfection.',
  '⌚',
  'story',
  'Business',
  'Ali Lotfi',
  25,
  '#FFF59D',
  true,
  false,
  4
);

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES

('d3e4f5a6-b7c8-9012-defa-234567890123', 0, 'The Orphan from Kulmbach', E'Imagine a lonely orphan boy in a small town in the corner of Europe, in Germany, during cold and gray times.\n\nHans Wilsdorf had no money and no support — but he had a dream in his head. With sheer determination, he went on to create Rolex, the watch that is today a symbol of precision and luxury.\n\nHans''s story isn''t just the tale of a watchmaker. It''s the story of a man who went from nothing to everything.\n\nBorn around 1881 in the small town of Kulmbach, Germany, Hans had two brothers. Their family was ordinary — his father was a local merchant who ran an iron hardware shop, and everything was going normally.\n\nBut fate had other plans. When Hans was 11, his mother fell ill and passed away. Within the next year, his father also became sick and died. Three brothers — completely orphaned, with no one in the world.', E'Hans''s story isn''t just the tale of a watchmaker. It''s the story of a man who went from nothing to everything.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 1, 'A Boarding School and a Spark', E'Their uncle became their guardian and made a wise decision: he sold their father''s iron shop, put the money in the bank to provide a monthly allowance, and enrolled all three boys in a top-tier boarding school.\n\nLife at the boarding school was tough. Most students were Catholic, but Hans came from a Protestant family and knew nothing about Catholic traditions. This cultural difference constantly caused tension — his classmates mocked him for being different.\n\nBut there was a silver lining. At that school, Hans learned French and English alongside his native German. These languages would become the most important pieces of his future puzzle — the ladder to his success.\n\nAt school, Hans befriended a Swiss boy who spoke French. This friend told stories about his hometown in Switzerland, where everyone''s livelihood revolved around watchmaking. The stories ignited something in Hans — a fascination with watches that would stay with him forever.', E'The languages he learned became the ladder to his success.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 2, 'Geneva: The Pearl Seller Becomes a Star', E'After graduating, Hans''s uncle suggested university. Hans refused. "I want to go to Geneva, Switzerland," he said. "I speak multiple languages, I want to work and earn money."\n\nHis first job in Geneva was as a salesman at a pearl shop. There, something remarkable happened. The boy who had been lonely and mocked at school discovered a hidden talent for connecting with people.\n\nHe became the store''s best salesman, earning commissions that exceeded those of senior staff — all at just 19 years old.\n\nThen a friend who worked at a Swiss watch company called Cuno & Korten suggested Hans join them. The moment Hans heard it, the childhood stories about watchmaking came flooding back. He quit the pearl shop immediately.\n\nThe watch company hired him on the spot — not to make watches, but to sell them. His English was invaluable. And during every free moment, Hans would rush upstairs to watch the repairmen work, quietly learning the craft of watchmaking.', E'He became the store''s best salesman at just 19 years old.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 3, 'London, Love, and the Birth of a Dream', E'After completing mandatory military service in Germany, Hans made a calculated move: he went to London — the wealthiest city of the time, where the best-paying customers were.\n\nThe first watch shop he visited hired him immediately. A multilingual watch expert? Any employer would have jumped at the chance.\n\nIn London, Hans met and married Florence. She wasn''t just a loyal wife — she supported him in every major business decision, backing his risks and providing emotional strength.\n\nFlorence''s older brother Alfred James was a successful merchant. During family gatherings, Hans would passionately talk about watches. One evening, Alfred said the words that changed everything:\n\n"You know so much about watches — why don''t you start your own brand?"\n\nHans hesitated, citing limited capital. Alfred replied: "You start. If you need money, come to me — I''ll lend it to you."\n\nThat conversation was the spark that lit the fire.', E'"You know so much about watches — why don''t you start your own brand?"'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 4, 'The Name That Changed Everything', E'In 1905, Hans and his brother-in-law registered a joint company. Smartly, Hans didn''t start with watchmaking — he began with manufacturing watch components, particularly mechanical movements.\n\nMeanwhile, Hans harbored a secret obsession: creating a men''s wristwatch. At the time, wristwatches didn''t exist for men. Only women wore them as jewelry — they were too small and inaccurate. Men relied on large, precise pocket watches.\n\nHans worked on this challenge during every spare moment — late nights, weekends, years of patient tinkering. In 1908, three years later, he finally succeeded: a men''s wristwatch as precise as the best pocket watches, yet small enough for the wrist.\n\nNow they needed a name. They tried various options — nothing felt right. Then someone threw out a made-up word: Rolex.\n\nHans and Alfred looked at each other. It was perfect — luxurious, memorable, and meaningless in any language. Universal. They registered the name immediately.', E'Rolex — luxurious, memorable, and universal.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 5, 'War, Wisdom, and the Move to Switzerland', E'When World War I erupted in 1914, 90% of European watch companies went bankrupt. But Rolex didn''t just survive — it thrived.\n\nThe German army needed precise watches for its officers. When they discovered Rolex made the most accurate wristwatches — perfect for the battlefield — they placed massive orders.\n\nBut the British government noticed Rolex was selling to the German army and imposed a 33% tax on those exports. Combined with growing anti-German sentiment in London (Hans''s German surname didn''t help), Hans made a pivotal decision: move the company to Geneva, Switzerland.\n\nSwitzerland was neutral, the global hub of watchmaking, and full of skilled craftsmen. The factory went to Bienne — a city famous for its watchmaking workshops. This decision proved brilliant: while competitors crumbled during the war, Rolex emerged stronger than ever, producing at the highest quality with the best Swiss talent.', E'While competitors crumbled during the war, Rolex emerged stronger than ever.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 6, 'The Prince, the Swimmer, and a Marketing Revolution', E'After WWI, Rolex was virtually unrivaled. Hans then made a genius marketing move: he gifted Rolex watches to influential figures.\n\nOne recipient was Prince Edward, the Prince of Wales. The prince loved the watch so much he wore it everywhere — to events, meetings, and public appearances. Suddenly, Rolex became the watch of aristocrats and elites.\n\nIn 1926, Rolex shocked the world again: the Oyster — the first waterproof watch. People were stunned. Could a watch really survive water?\n\nIn 1927, Hans learned that swimmer Mercedes Gleitze was planning to swim the English Channel. He saw an opportunity: he gave her a Rolex Oyster to wear around her neck during the 10-hour swim.\n\nWhen she reached the other shore, the watch was checked — not a single drop of water had entered. It was working perfectly. The news exploded across every newspaper. Rolex wasn''t just a luxury watch anymore — it was an adventure companion.', E'Rolex wasn''t just a luxury watch anymore — it was an adventure companion.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 7, 'Three Shocks to the World', E'In 1931, Hans delivered the third shock to the watch industry: the Oyster Perpetual — the first automatic, self-winding watch that never needed manual winding.\n\nBefore this, all watches had to be wound daily. Rolex''s perpetual mechanism changed everything. A waterproof, automatic watch? It was revolutionary.\n\nHans kept following his golden rule: if something works, keep doing it. After the swimmer collaboration, he sponsored Arctic explorers — Rolex went to the North Pole and survived. Later, Rolex became the first watch to reach the summit of Mount Everest.\n\nEach adventure proved the same message: Rolex is precise, durable, and unbreakable.\n\nWhen World War II came, every army in Europe wanted Rolex watches. And because Hans had long ensured the Rolex brand stood independent of his German name, the company sailed through the anti-German sentiment unscathed.\n\nBy the end of WWII, Rolex wasn''t just luxury — it was the watch everyone aspired to own.', E'If something works, keep doing it.'),

('d3e4f5a6-b7c8-9012-defa-234567890123', 8, 'The Legacy of Hans Wilsdorf', E'Two final lessons from Hans''s life:\n\nFirst, Hans always preferred to stay behind the scenes. He wanted the Rolex brand to speak for itself — never dependent on his personal fame. This independence allowed him to travel the world, drawing inspiration from different cultures for new watch designs and understanding diverse market needs.\n\nEvery trip he took was followed by Rolex flourishing in that region. He was a lifelong learner and adventurer, and that curiosity fueled his success.\n\nSecond, Hans created a company culture of pride and respect. He was one of the first business leaders to build a positive, empowering workplace. He organized trips for employees to visit Rolex offices around the world — not just for learning, but to make every employee feel trusted, valued, and proud to be part of Rolex.\n\nHans Wilsdorf started with a dream. He crossed through every challenge, and built Rolex into one of the most recognized symbols of luxury in the world.\n\nFirst, it was a symbol of precision. During war, it became a symbol of quality. Then it became a symbol of luxury. And finally — a symbol of loyalty, respect, and pride.', E'First precision, then quality, then luxury, and finally — a symbol of loyalty, respect, and pride.');

-- McDonald's Story
INSERT INTO reading_content (id, title, subtitle, description, emoji, type, category, author, reading_time_minutes, theme_color, is_published, is_premium, sort_order)
VALUES (
  'e4f5a6b7-c8d9-0123-efab-345678901234',
  'Ray Kroc: The McDonald''s Story',
  'From Paper Cup Salesman to Fast Food King',
  'The remarkable story of Ray Kroc — a high school dropout who sold paper cups and milkshake machines for decades before discovering a small hamburger stand in California at age 52. How he turned it into the world''s largest fast food empire.',
  '🍔',
  'story',
  'Business',
  'Ali Lotfi',
  30,
  '#FFD6E8',
  true,
  false,
  5
);

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES

('e4f5a6b7-c8d9-0123-efab-345678901234', 0, 'A Boy Who Hated School', E'The founder of the world''s fast food giant McDonald''s once said: "I have always believed that each person is responsible for their own problems, and each person is the cause of their own happiness."\n\nRay Kroc was born in 1902 in Oak Park, a western suburb of Chicago. His father Louis was an electrical technician at a large company. His younger brother Bob became a medical specialist. But Ray? He had no interest in school whatsoever.\n\nWhat Ray did have was a sharp instinct for business. As a child, he worked at his uncle''s pharmacy and saved every penny of his summer wages. He and two friends pooled their savings — $100 total — to open a small music instrument store. It failed within months.\n\n"It was a bitter experience," Ray recalled, "but it taught me a great lesson: a deeper sense of responsibility toward work and life."\n\nWhen World War I began, 14-year-old Ray dropped out of school. He joined the army as a Red Cross ambulance driver — but the war ended before he was deployed.', E'Each person is responsible for their own problems, and each person is the cause of their own happiness.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 1, 'The Paper Cup Hustler', E'After the war, Ray bounced between jobs — a fabric store clerk, then a piano player in a Chicago band (his mother had taught him piano). He married his first wife Ethel in 1920 and knew he needed stable income.\n\nHe found work at Lily-Tulip, a company that made paper cups. "Don''t think selling paper cups was easy," Ray recalled. "In 1922, I''d grab a bunch of samples and walk the streets of Chicago, door to door, from 7 AM to 5 PM."\n\nBut at 5 PM, Ray didn''t go home. He went to his second job — playing piano at a Chicago radio station, from 5 PM until 2 AM.\n\n"The work was long and grueling, but I never let exhaustion stop me," he said. "I learned that in life you must cultivate endurance, persistence, and resilience within yourself."\n\nHis motto: "One of my secrets to success is making the most of every single minute of rest. I averaged 6 hours of sleep, sometimes even 4. I despised wasting even one minute."', E'I never let exhaustion stop me. I learned to cultivate endurance, persistence, and resilience.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 2, 'The Salesman Who Wouldn''t Back Down', E'By 1925, Ray became the #1 salesman in the entire paper cup company. But he hit a ceiling — and took a bold detour.\n\nHe took 5 months of unpaid leave and drove to Florida, the "land of opportunity." There, he joined a real estate firm and quickly became one of their top 20 salespeople, earning a car with a driver at just 23.\n\nBut the Florida real estate market crashed after negative press. Ray returned to Chicago and his paper cup job — wiser now. He targeted new venues: stadiums, horse racing tracks, zoos, beaches, and candy shops.\n\nThen came a test of character. His boss called him in privately: the company was in financial trouble and would cut salaries. Ray, their best salesman, was outraged.\n\n"I couldn''t accept being treated like a burden," he said. "I had brought enormous profits to this company." He resigned on the spot.\n\nThe stunned boss eventually called back with a special deal to preserve Ray''s compensation. Ray accepted — and learned a powerful lesson: "Standing firm in your rightful position always pays off."', E'Standing firm in your rightful position always pays off.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 3, 'The Milkshake Machine Years', E'In 1936, Ray met Earl Prince, an engineer who owned ice cream parlors and had invented a multi-spindle milkshake mixer. Prince offered Ray exclusive rights to sell the machines across the country — 50/50 profit split.\n\nRay threw himself into it. The early years were tough — restaurant managers saw no reason to replace their existing mixers. But Ray was relentless. He attended every industry event, visited every restaurant association meeting, and networked constantly.\n\nBy 1948, he set a record: 8,000 mixers sold in a single year.\n\nBut the real turning point was still ahead. Among his clients were two brothers in California who had ordered eight mixers. Each mixer could make six milkshakes simultaneously — meaning they were preparing 48 milkshakes at once.\n\n"Their business must be booming," Ray thought. He put visiting them at the top of his list.\n\nThat visit would change his life — and the entire food industry — forever.', E'That visit would change his life — and the entire food industry — forever.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 4, 'The Visit That Changed Everything', E'When Ray arrived at the McDonald brothers'' restaurant in San Bernardino, California, he saw something he had never seen before.\n\nThe quality of the production line. The cleanliness. The speed of service. "I was deeply impressed," he recalled.\n\nWorkers in matching white uniforms and identical caps moved like a military parade. Packages of fries, meat, and soda boxes flowed into the kitchen with perfect rhythm. The parking lot was overflowing. A long line stretched at the counter.\n\n"I thought to myself: how wasteful that such an amazing operation is limited to just one location."\n\nThat night at his hotel, Ray couldn''t sleep. In his mind, he saw McDonald''s restaurants across the entire country — like a movie playing before his eyes.\n\nThe next morning, he went straight to the brothers with a proposal: let me open identical restaurants nationwide. When one brother protested that managing more locations would be impossible, Ray didn''t hesitate:\n\n"I''ll do it myself."', E'"How wasteful that such an amazing operation is limited to just one location."'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 5, 'The Golden Contract', E'On the flight back to Chicago, Ray clutched his briefcase like it contained millions in cash. In a way, it did — inside was a signed contract with the McDonald brothers giving him the right to open franchises across America.\n\nThe terms: every restaurant had to look identical, serve the same menu, and follow the same standards. Any changes required written approval from the brothers. Ray would receive about 2% of all restaurant revenues. Each new franchise paid $950 to Ray, and each license lasted 20 years.\n\nBack in Chicago, Ray told his friends about his plan. Most laughed: "Making money from cheap hamburgers and fries? That''s madness!"\n\nOnly one friend, Art, believed in him. Ray convinced Art to manage the first restaurant.\n\nIn 1955, Ray opened his first McDonald''s in the western suburbs of Chicago. He was 52 years old.\n\n"Every morning before my mixer job started, I''d go to the restaurant and help the staff," he said. "I didn''t consider it beneath me to clean the bathrooms and mop the floors."', E'Most laughed: "Making money from cheap hamburgers? That''s madness!"'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 6, 'Obsession with Quality', E'Ray encountered immediate challenges. The building design, perfect for sunny California, didn''t work in freezing Chicago. The French fries tasted wrong — in California, potatoes dried naturally in the warm breeze, but Chicago''s cold climate needed a different solution.\n\nRay innovated: he built a ventilation system in the basement to dry the potatoes. He begged the McDonald brothers to adapt building designs for different climates, but they refused to budge.\n\nDespite the obstacles, Ray was fanatical about three things: Quality, Service, and Cleanliness.\n\n"If I received a brick for every time I emphasized quality, service, and cleanliness," he said, "I could have built a bridge across the Atlantic Ocean."\n\nHe created exhaustive manuals detailing every aspect of operations: exact cooking times, temperatures measured by thermometer, how hamburgers should be arranged, how employees should smile, how to greet customers, even how to maintain eye contact.\n\nA hamburger not sold within 10 minutes? Throw it away. No exceptions.', E'If I received a brick for every time I emphasized quality, service, and cleanliness, I could have built a bridge across the Atlantic.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 7, 'The Real Estate Genius Move', E'By 1956, Ray had opened 8 more restaurants. But he needed to scale faster — and he found a brilliant strategy.\n\nLandowners across America had properties mortgaged to banks. Ray approached them with an offer: "Let me lease your land. I''ll pay your monthly mortgage installments."\n\nIt was a win-win: idle properties became income-generating, and Ray avoided the massive cost of buying land outright. The rent from McDonald''s franchisees covered the mortgage payments.\n\nThis formula worked beautifully. Ray also built a circle of key advisors — accountants, lawyers, financial consultants. "My greater success was because of the successful people I chose and the important tasks I entrusted to them," he said.\n\nYear after year, the chain grew. Then came the moment Ray had been waiting for: buying out the McDonald brothers entirely. When they named their price — $2.7 million — Ray nearly fainted. But he found a way to finance it.\n\nHe calculated it would take until 1991 to pay off the debt. Instead, the chain grew so fast he paid it off by 1972 — in just 11 years.', E'My greater success was because of the successful people I chose and the important tasks I entrusted to them.'),

('e4f5a6b7-c8d9-0123-efab-345678901234', 8, 'The Empire Builder', E'By 1977, McDonald''s had 4,177 restaurants in America and 21 abroad, generating $3 million in daily sales.\n\nRay never stopped working. The company gave him a private plane to visit locations and scout new sites — especially near churches and schools.\n\n"I''m always eager to personally visit different McDonald''s branches, near and far," he said. "Sometimes I see things that kill my enthusiasm — a sign that''s still off at night, or garbage piled up in the parking lot. When I see these things, I get furious. Others might not care about these details, but to me, this carelessness is an insult."\n\nEven in his later years, Ray traveled constantly despite chronic pain in his hip and back. His philosophy: "Pain and suffering are more bearable than idleness and laziness."\n\nWhen someone once told him, "It''s easy for a man with millions to talk about hard work and success," Ray fired back:\n\n"Don''t forget — I can only wear one pair of shoes at a time, just like everyone else."', E'Pain and suffering are more bearable than idleness and laziness.');
