INSERT INTO reading_content (id, title, subtitle, description, emoji, type, category, author, reading_time_minutes, theme_color, cover_aspect, is_published, is_premium, sort_order)
VALUES (
  'e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8',
  '27 Financial Leakages',
  'Hidden behaviors draining your wallet',
  'Discover the 27 subtle behavioral patterns that silently drain your money — and learn how to plug each one.',
  '🚿',
  'lesson',
  'money',
  'LadyBoss',
  15,
  '#FFD6E0',
  'square',
  true,
  false,
  25
);

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 0, 'The Invisible Drip: Why Your Money Disappears', 'Have you ever looked at your bank account at the end of the month and wondered where it all went? You worked hard, you earned well, yet the balance doesn''t reflect your effort. Think of your finances like a bucket filled with water. You can keep pouring more in (earning more), but if the bucket has twenty-seven tiny holes in the bottom, it will never stay full. These ''leaks'' are often invisible, driven by deep-seated psychological patterns rather than a lack of math skills. By identifying these behavioral leaks, you stop the drip and start building true wealth. This journey isn''t about restriction; it''s about empowerment and making sure your money stays where it belongs: with you.', 'Financial freedom isn''t just about how much you make; it''s about how much you keep.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 1, 'The Emotional Rollercoaster: Mood-Driven Leaks', 'Our moods often dictate our spending more than our blueprints. Emotional Peak Shopping happens when you''re riding high on a promotion or crashing from a breakup; in those moments, logic exits the room. This is cousin to Despair-Based Spending, where you spend recklessly because you feel hopeless about the future, and ''Dam-Break'' Spending, which occurs after you''ve been too restrictive for too long and suddenly splurge everything at once. Finally, Love at First Sight is that magnetic pull toward a dress or gadget that makes you feel like you can''t leave the store without it. To counter these, implement a 48-hour ''cooling off'' rule for any unplanned purchase.', 'Don''t let a temporary emotion create a permanent dent in your savings.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 2, 'The Perfectionist''s Trap: Idealism and the Past', 'Sometimes we spend to heal old wounds or create a perfect reality. Childhood Complex Buying happens when you overcompensate for things you lacked growing up, often buying toys or clothes for your kids (or yourself) that go beyond necessity. Perfectionist Buying is the urge to have the ''complete set'' — if you buy the yoga mat, you feel you must buy the matching blocks, towel, and bag. This often stems from Idealistic Behavior, assuming your finances will magically stay ''fine'' without a concrete plan. To break this, ask yourself: ''Am I buying this for my current reality, or a fantasy version of myself?''', 'You don''t need a ''perfect'' set to live a purposeful life.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 3, 'The Social Mirror: Spending for Connection and Competition', 'Human beings are social creatures, but our circles can be expensive. Herd Behavior is the ''me too'' effect — buying an air fryer or a designer bag just because three friends did. This often leads to Friendship-Chain Buying, where the bill climbs during social outings because you don''t want to be the one to suggest a cheaper venue. Worse is Jealousy & Keeping Up, where money is used as a weapon to match or outdo a peer''s lifestyle. Remember, your friends aren''t paying your credit card bill. Genuine connection doesn''t require a high price tag; suggest a home-cooked meal or a park walk instead.', 'True friends value your presence, not your purchases.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 4, 'The Validation Vacuum: Seeking Approval Through Money', 'When we base our value on what others think, our bank accounts suffer. Approval-Seeking Spending is the habit of people-pleasing through your wallet, while Social Validation Spending is about projecting an image of success that might not exist. This is closely linked to Buying Based on Others'' Opinions, where you let a salesperson or an influencer tell you what you ''need.'' Even Dominance Behavior — spending to show you are the ''alpha'' in a group — falls into this category. To stop this leak, practice the mantra: ''I have nothing to prove and no one to impress.''', 'Budgeting for the sake of your reputation is a race you will never win.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 5, 'The Mindset Gap: YOLO vs. Survivalism', 'We often justify leaks with catchy slogans. The ''YOLO'' (You Only Live Once) Mentality is the ultimate justification for living beyond your means today at the expense of your 60-year-old self. Similarly, Future Anxiety Buying is the flip side — hoarding items or spending out of fear because the world feels unstable. We also fall for the Bulk Buying Trap, thinking we''re saving money by purchasing 50 units of something we don''t actually need or have space for. Balance ''living for today'' with ''loving your future self.'' Real security comes from a solid emergency fund, not a closet full of panic-bought goods.', 'Living for today shouldn''t mean bankrupting your tomorrow.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 6, 'The Caretaker''s Leak: Sacrifice and Pity', 'High-achieving women often fall into the trap of Excessive Self-Sacrifice, giving away their savings to family or friends while their own needs go unmet. We also see Pity Purchases — buying things you don''t want just because you feel sorry for the salesperson or a struggling business. Living Others'' Dreams is another subtle leak, where you spend money on a career path or lifestyle your parents or partner wanted for you. It''s okay to be generous, but you must put on your own financial oxygen mask first. Setting boundaries isn''t selfish; it''s sustainable.', 'You cannot pour from an empty cup — or an empty bank account.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 7, 'The Convenience Cost: Laziness and Aesthetics', 'Sometimes we lose money simply because we aren''t paying attention. The Laziness Tax is the extra $10 you pay for delivery because you didn''t want to drive, or the subscriptions you never cancelled. Design-Based Buying happens when a store''s beautiful layout or ''aesthetic'' packaging tricks your brain into an unplanned purchase. We also see the Update/Upgrade Obsession, where you replace a perfectly functional phone just because the new one has a slightly better camera. Audit your recurring transactions this week — you''ll likely find at least two ''laziness'' leaks you can plug immediately.', 'A small leak can sink a great ship; watch the ''convenience'' costs.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 8, 'The Quality Quandary: Growth vs. Clutter', 'Does your spending help you grow? Non-Evolutionary Purchases are things that don''t add value to your skills, health, or future. This often goes hand-in-hand with Low-Quality Purchases — buying the ''cheap'' version that breaks in a month, forcing you to buy it again (the ''poor man''s tax''). Another major risk is the Impulsive Business Launch — spending thousands on branding and inventory for a ''passion project'' without a validated business plan. Invest in things that have a ''Return on Life'' or a ''Return on Investment,'' rather than just filling space.', 'Buy it nice, or buy it twice. Focus on value over price.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 9, 'The Weight of Tradition: Customs and Expectations', 'Cultural/Traditional Spending is a significant leak for many, where we spend beyond our means on weddings, funerals, or festivals due to societal pressure. This often leads back to that ''idealistic'' view that the money will just ''show up'' later. While honoring heritage is beautiful, doing it with borrowed money creates a legacy of debt. Learn to celebrate within your current means. True tradition is about the spirit of the occasion, not the size of the centerpiece. Courageous women are those who have the strength to say, ''We are doing this differently this year.''', 'Respect your roots, but protect your fruits. Your future is a priority.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 10, 'The Mirror Test: Identifying Your Personal Leaks', 'Now that you know the 27 leakages, it''s time for a ''Financial Audit.'' Take your bank statements from the last three months and three highlighters. Color-code your expenses: Green for essentials, Yellow for intentional joy, and Red for leakages. Which of the 27 names keeps popping up? Is it ''Laziness Tax''? ''Social Validation''? Don''t judge yourself — this isn''t about guilt, it''s about data. Identification is 50% of the cure. Once you name the leak, you take away its power to go unnoticed.', 'Awareness is the first step toward transformation. Name your leaks to tame them.');

INSERT INTO reading_sections (content_id, sort_order, heading, body, quote)
VALUES ('e4f5a6b7-c8d9-4e0f-a1b2-c3d4e5f6a7b8', 11, 'The Wealthy Woman''s Blueprint: Taking Back Control', 'You now hold the map of 27 financial leakages. This knowledge alone sets you apart from 95% of people who never examine their spending behavior. Start small: pick your top three leakages this week, and commit to a single counter-strategy for each. Track your progress in a journal. Share what you''ve learned with a friend — teaching reinforces learning. Remember, plugging leaks is not about deprivation; it''s about redirection. Every dollar you save is a dollar you can invest in your dreams, your business, or your family''s future. You are not just saving money; you are building your legacy as a LadyBoss.', 'Every dollar you save by plugging a leak is a seed planted for your freedom.');