
-- Story 1: Sara Blakely
WITH s1 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'Sara Blakely: The $5,000 Gamble',
    'From fax machines to a billion-dollar empire',
    'This is the story of a woman who spent seven years being rejected at front doors before she changed the way the world gets dressed. It''s a story of white pantyhose, cold calls, and a pair of scissors that turned $5,000 into a billion-dollar empire.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#FFE0F5',
    '✂️',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s1), 0, 'The Girl Who Failed Everything', E'In the early 90s, Sara Blakely\u2019s life looked like a series of dead ends. Her dream was to be a trial attorney like her father, but she failed the LSAT\u2014twice. Desperate for a job, she headed to Disney World to audition for the role of Goofy. She was told she was too short.\n\nShe ended up as an attendant at a ride in Epcot, wearing a polyester uniform and buckled shoes, ushering people onto a moving walkway. While her friends were starting law careers or getting promoted, Sara was at the \u201CLiving with the Land\u201D attraction, wondering if this was as good as it was ever going to get.', 'Failure is not the outcome; failure is not trying.'),
((SELECT id FROM s1), 1, 'The Cold Call Queen', E'Sara eventually traded the Disney uniform for a beige suit and a heavy box of fax machines. For seven years, she worked for a company called Danka, driving through the sweltering heat of Clearwater, Florida. Her job was \u201Ccold calling\u201D\u2014walking into office buildings where she wasn\u2019t invited and trying to convince grumpy office managers to buy a piece of equipment they didn\u2019t want.\n\nShe was kicked out of buildings. She had her car towed. She cried in gas station parking lots. But in those seven years of \u201CNo,\u201D she learned something most people never do: how to handle a door being slammed in her face without letting it bruise her soul. She was accidentally training for the fight of her life.', 'Seven years of "No" taught her what no business school ever could.'),
((SELECT id FROM s1), 2, 'The Scissors and the "Aha!" Moment', E'It was a humid Florida night in 1998, and Sara was getting ready for a party. She wanted to wear a pair of cream-colored slacks, but she hated the way her underwear showed through the fabric. She tried on a pair of control-top pantyhose to smooth things out, but she hated the \u201Cseam\u201D at the toe and the way the stockings looked with her open-toed sandals.\n\nShe stood in her bathroom, looking in the mirror, and grabbed a pair of kitchen scissors. She cut the feet off the pantyhose. That night, she felt confident. She felt smooth. But as the night went on, the nylon rolled up her legs like a window shade. She realized two things: the product she wanted didn\u2019t exist, and she was the only one crazy enough to invent it.', 'The product she wanted didn''t exist—and she was the only one crazy enough to invent it.'),
((SELECT id FROM s1), 3, 'The Secret Research', E'Sara didn\u2019t tell anyone what she was doing. For a year, she kept her \u201CProject\u201D a secret, working her fax machine job by day and researching the hosiery industry by night. She spent her weekends at the Georgia Tech library, reading every patent ever filed for stockings.\n\nShe didn\u2019t have a fashion degree. She didn\u2019t have a business partner. She just had $5,000 in savings and a yellow legal pad. She realized that the hosiery industry was run by men who didn\u2019t actually wear the products they made. They were making stockings for a \u201Cbody type\u201D that didn\u2019t exist, using waistbands that pinched and fabrics that itched.', 'She had $5,000 in savings, a yellow legal pad, and an industry that had never listened to its own customers.'),
((SELECT id FROM s1), 4, 'The North Carolina Road Trip', E'With her $5,000 in her pocket, Sara drove to North Carolina, the hosiery capital of the world. She walked into massive mills, unannounced, asking the owners to manufacture her \u201Cfootless pantyhose.\u201D\n\nThe owners\u2014mostly men in their 60s and 70s\u2014looked at this 27-year-old girl like she was insane. \u201CWho are you with?\u201D they asked. \u201CSara Blakely,\u201D she replied. \u201CAnd who is backing you?\u201D \u201CMe.\u201D They laughed her out of their offices. She was an outsider in an old-school world, trying to explain \u201Cshapewear\u201D to people who had never worn a girdle in their lives.', '"Who is backing you?" "Me." They laughed her out of their offices.'),
((SELECT id FROM s1), 5, 'The Phone Call from the Future', E'Two weeks after her disastrous trip to North Carolina, Sara got a phone call. It was one of the mill owners she had visited. \u201CI\u2019ve decided to help you,\u201D he said.\n\nSara was stunned. \u201CWhy?\u201D\n\n\u201CI have two daughters,\u201D the man replied. \u201CI went home and told them about your crazy idea, and they nearly tackled me. They said, \u2018Dad, you have to make this. We\u2019ve been waiting for this our whole lives.\u2019\u201D A few daughters in a living room had seen what a room full of male executives couldn\u2019t: a revolution in a blue-and-red box.', 'A few daughters in a living room saw what a room full of executives couldn''t.'),
((SELECT id FROM s1), 6, 'The Trademark and the Name', E'Sara knew she needed a name that stuck. She spent weeks driving around, saying random words out loud. She knew that Kodak and Coca-Cola were successful because of the \u201CK\u201D sound. One day, while sitting in traffic, the word \u201CSpanks\u201D popped into her head.\n\nShe changed the \u201Cks\u201D to an \u201Cx\u201D at the last minute\u2014partly because it looked edgier, and partly because it was easier to trademark. She wrote her own patent application using a textbook she bought at Barnes & Noble because she couldn\u2019t afford a lawyer. She was a one-woman army, doing the legal, the creative, and the logistical work from her dining room table.', 'She was a one-woman army—doing the legal, the creative, and the logistics from her dining room table.'),
((SELECT id FROM s1), 7, 'The Neiman Marcus Bathroom Demo', E'After a year of perfecting the prototype, Sara landed a meeting with a buyer at Neiman Marcus in Dallas. She had ten minutes to make her case. She could see the buyer\u2019s eyes glazing over as she talked about \u201Cdenier\u201D and \u201Cknitting patterns.\u201D\n\nSara stopped talking. \u201CCome with me to the bathroom,\u201D she said. The buyer, confused, followed her. Sara went into a stall, put on her Spanx under her trousers, and came out. Then she took them off and showed the buyer the difference. The buyer looked at Sara\u2019s silhouette, then at the product, and said, \u201CI get it. I\u2019ll take it in seven stores.\u201D', 'She stopped the pitch and said, "Come with me to the bathroom." That''s when everything changed.'),
((SELECT id FROM s1), 8, 'The Oprah Moment', E'Spanx was growing, but it was still a \u201Csmall\u201D business run out of Sara\u2019s apartment. She was still the one shipping boxes and answering the phones in different voices so it sounded like she had a \u201Ccustomer service department.\u201D\n\nThen, in 2000, she sent a basket of Spanx to Oprah Winfrey\u2019s stylist. A few weeks later, Sara was sitting on her floor, exhausted, when she saw Oprah on TV. Oprah announced that Spanx was her \u201CFavorite Product of the Year.\u201D\n\nThe website (which Sara had built herself for a few hundred dollars) crashed almost instantly. The \u201Csmall\u201D business was gone. Overnight, Sara Blakely became a household name.', 'The website crashed. The "small" business was gone. Overnight, she became a household name.'),
((SELECT id FROM s1), 9, 'The Billionaire in Red Heels', E'By 2012, Sara Blakely was named the youngest self-made female billionaire in the world. She still owned 100% of her company. She had never spent a dime on traditional advertising\u2014relying entirely on the \u201Cword of mouth\u201D of women who finally felt comfortable in their own clothes.\n\nShe proved that you don\u2019t need an MBA or a law degree to build an empire. You just need the grit to stay in the room when everyone is telling you to leave, and the courage to use kitchen scissors on a perfectly good pair of stockings. Today, Spanx is a global icon, but to Sara, it\u2019s still just the result of a $5,000 gamble and a refusal to go home as a failure.', 'The only thing that''s going to stop you is the fear of looking stupid. Once you stop caring about that, you''re dangerous.');

-- Story 2: Coco Chanel
WITH s2 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'Coco Chanel: The Architecture of Freedom',
    'From orphanage shadows to the throne of fashion',
    'This is the story of a girl who was born into the deepest shadows of France and used a pair of scissors to cut her way into the light. It is a story of black lace, white camellias, and a scent that changed the world forever.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#F0E3FF',
    '🖤',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s2), 0, 'The Abbey of Shadows', E'In 1895, a twelve-year-old girl named Gabrielle Chanel stood at the iron gates of the Aubazine Abbey, a cold, stone orphanage in the heart of France. Her mother was dead; her father, a wandering peddler, had simply dropped her off and never returned.\n\nLife at the abbey was stripped of all color. The nuns wore strict black habits with white collars. The floors were scrubbed with lye until they were bone-white. Gabrielle spent her days sewing in silence, her fingers moving rhythmically through rough fabrics. But even in this prison of grey, she was observing. She stared at the patterns in the stained-glass windows\u2014interlocking \u201CC\u201D shapes that would one day become the most famous logo in history. She learned that there was a hidden power in simplicity, and a quiet authority in black and white.', 'In this prison of grey, she found a hidden power in simplicity.'),
((SELECT id FROM s2), 1, '"Qui qu''a vu Coco?"', E'By age eighteen, Gabrielle had left the orphanage and was working as a seamstress by day and a cabaret singer by night in a town frequented by cavalry officers. She only knew two songs. One was about a lost dog named Coco. Every night, the soldiers would cheer and shout, \u201CCoco! Coco!\u201D The nickname stuck. Gabrielle hated it at first\u2014it was a \u201Cstage name\u201D for a girl who had nothing. But she soon realized that Gabrielle was the orphan, while \u201CCoco\u201D could be whoever she wanted to be. She began to craft a persona. She didn\u2019t look like the other girls in town with their giant, feathered hats and tight corsets. She dressed in men\u2019s riding breeches and flat boater hats. She looked like a rebel in a world of dolls.', 'Gabrielle was the orphan. "Coco" could be whoever she wanted to be.'),
((SELECT id FROM s2), 2, 'The Apartment at Boulevard Malesherbes', E'Coco eventually moved to Paris, supported by a wealthy polo player named \u00C9tienne Balsan. She lived in his grand chateau, surrounded by the French elite, but she refused to be a \u201Ckept woman.\u201D While the other ladies spent their afternoons gossiping, Coco was in the basement, taking apart old hats and rebuilding them.\n\nShe stripped away the fake flowers, the heavy veils, and the dead birds that were fashionable at the time. She created \u201CChanel Modes\u201D\u2014hats that were small, architectural, and sharp. In 1910, with the help of her true love, an English businessman named Boy Capel, she opened her first shop at 21 Rue Cambon. She was no longer a singer; she was a milliner.', 'She stripped away everything fake and built something sharp, clean, and entirely her own.'),
((SELECT id FROM s2), 3, 'The Jersey Revolution', E'When World War I broke out, the fabric industry collapsed. Fine silk and expensive lace disappeared. Most designers panicked, but Coco saw an opportunity in the \u201Cimpossible.\u201D She went to a warehouse and bought a massive surplus of jersey\u2014a cheap, scratchy fabric used only for men\u2019s underwear.\n\nShe began draping the jersey directly onto her own body. She got rid of the corset entirely, allowing women to breathe, to walk, and to drive cars. She moved her business to the seaside town of Deauville, where the wealthy were hiding from the war. When they saw Coco walking on the beach in her loose, jersey sweaters and tanned skin, they were horrified\u2014and then they were obsessed. She had turned \u201Cpoverty\u201D into the ultimate luxury.', 'She turned poverty into the ultimate luxury.'),
((SELECT id FROM s2), 4, 'The Little Black Dress (LBD)', E'Before 1926, black was the color of mourning. It was the color of death and the color of servants. Then, Vogue published a sketch of a simple, long-sleeved dress in black cr\u00EApe de chine, designed by Chanel. They called it \u201CThe Chanel Ford\u201D\u2014a dress so perfect it could be \u201Cavailable to the masses.\u201D Coco had taken the uniform of the nuns who raised her and turned it into the uniform of the modern woman. She stripped away the buttons and the bows. \u201CInnocence is the opposite of luxury,\u201D she said. She wanted women to be the hero of the room, not the dress. The LBD became a social equalizer; you couldn\u2019t tell if a woman was a duchess or a secretary, and that was exactly how Coco wanted it.', 'She wanted women to be the hero of the room—not the dress.'),
((SELECT id FROM s2), 5, 'The Fifth Sample', E'In 1921, Coco wanted to create a perfume that \u201Csmelled like a woman, not a flower.\u201D At the time, perfumes were either heavy musks or single-flower scents like rose. She met a master perfumer named Ernest Beaux in Grasse, the perfume capital of the world.\n\nBeaux prepared ten glass vials for her to test. He numbered them 1 through 5, and 20 through 24. Coco picked up the fifth bottle. It was a complex explosion of eighty ingredients, including a massive dose of aldehydes\u2014chemicals that made the scent \u201Csparkle\u201D like champagne. \u201CI present my dress collections on the fifth of May, the fifth month of the year,\u201D she said. \u201CSo we will let this sample keep the number it has. It will bring luck.\u201D She put it in a simple, laboratory-style bottle with a clean white label. It was the birth of Chanel No. 5.', 'She picked the fifth bottle. It would become the most famous scent in history.'),
((SELECT id FROM s2), 6, 'The Mirrored Staircase', E'Coco\u2019s headquarters at 31 Rue Cambon became a temple of style. The most famous feature was the spiral staircase lined with mirrors. During her fashion shows, Coco would sit at the very top of the stairs, hidden from view, watching the reflections of the audience\u2019s faces below.\n\nShe could see which dresses made them gasp and which made them whisper. She was the ghost in the machine, controlling the narrative of French elegance without ever showing her own face. She worked with her scissors hanging from a ribbon around her neck, often kneeling on the floor to rip apart a sleeve in the middle of a fitting if the \u201Cline\u201D wasn\u2019t perfect.', 'She was the ghost in the machine—controlling elegance without ever showing her face.'),
((SELECT id FROM s2), 7, 'The Great Exile', E'World War II brought Coco\u2019s empire to a screeching halt. She closed her shops, saying it was \u201Cno time for fashion.\u201D During the Nazi occupation of Paris, her life became complicated and controversial. She stayed at the Ritz Hotel, and her associations during the war led to a deep blow to her reputation.\n\nWhen the war ended, the French public turned against her. She was seen as a relic of a dark time. In 1945, she packed her bags and went into exile in Switzerland. For almost ten years, the House of Chanel was quiet. A new designer, Christian Dior, took over with his \u201CNew Look\u201D\u2014heavy skirts and tight waists. Coco watched from afar, disgusted. \u201CDior doesn\u2019t dress women,\u201D she snapped. \u201CHe upholsters them.\u201D', '"Dior doesn''t dress women. He upholsters them."'),
((SELECT id FROM s2), 8, 'The Seventy-Year-Old Comeback', E'In 1954, at the age of seventy-one, Coco Chanel decided she had seen enough. She returned to Paris to reclaim her throne. Her comeback show was a disaster in France. The critics laughed at her \u201Cdated\u201D tweed suits. They said she was finished.\n\nBut across the ocean, the American press saw something different. Life magazine wrote, \u201CAt 71, Gabrielle Chanel is bringing more than a style\u2014she is bringing a revolution.\u201D American women, who were entering the workforce in record numbers, didn\u2019t want Dior\u2019s corsets; they wanted Chanel\u2019s freedom. The \u201CChanel Suit\u201D became the global standard for the powerful woman. It was functional, it was chic, and it was indestructible.', 'At 71, she didn''t just bring a style—she brought a revolution.'),
((SELECT id FROM s2), 9, 'The Last Seamstress', E'Coco Chanel worked until the very last day of her life. She died in 1971 in her room at the Ritz, across the street from her shop. She left behind no children and no husband\u2014only a name that meant more than any title.\n\nShe had taken the \u201Cmusic\u201D of her Uncle\u2019s kitchen and the \u201Cshadows\u201D of the orphanage and built a language that every woman in the world now speaks. From the quilted handbag with the gold chain (designed so she could keep her hands free) to the two-tone shoe, she proved that fashion is fleeting, but \u201Cstyle\u201D is the ultimate act of self-command.', 'My life didn''t please me, so I created my life.');

-- Story 3: Melanie Perkins
WITH s3 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'Melanie Perkins: The Design Democrat',
    'From a living room in Perth to a global design empire',
    'This is the story of a woman from Perth, Australia, who was told "no" by over 100 venture capitalists before she built the tool that changed how the world sees design. It is a story of kiteboarding, high school yearbooks, and the determination to make the "impossible" simple.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#D7E9FF',
    '🎨',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s3), 0, 'The Living Room Lab', E'In 2007, the \u201Ctech capital\u201D of the world was Silicon Valley, but Melanie Perkins was 9,000 miles away in Perth, Australia. She was a 19-year-old university student sitting at her mother\u2019s wooden dining table, trying to teach fellow students how to use professional design software like Photoshop and InDesign.\n\nShe watched them struggle for hours just to perform simple tasks\u2014aligning a text box or changing a font. The software was \u201Cclunky,\u201D expensive, and required a semester of learning just to create a basic flyer. Melanie had a \u201CNotice\u201D moment: why did design have to be so hard? Why couldn\u2019t it be online, collaborative, and simple? She turned to her boyfriend, Cliff Obrecht, and said, \u201CThe future of design should be a place where everyone can participate.\u201D', 'The future of design should be a place where everyone can participate.'),
((SELECT id FROM s3), 1, 'The Yearbook Test (Fusion Books)', E'Melanie and Cliff didn\u2019t have millions of dollars or a team of engineers. They had a small credit card limit and a big idea. They decided to test their concept in a \u201Cniche\u201D market: high school yearbooks. They started a company called Fusion Books out of Melanie\u2019s mother\u2019s living room.\n\nThis was the \u201Cwhere\u201D of Canva\u2019s birth. They converted the living room into an office, and for five years, they managed every part of the process. They built a simple drag-and-drop tool that allowed students to design their own yearbooks. Melanie\u2019s mother would often come into the \u201Coffice\u201D to find them surrounded by stacks of paper and printing proofs. Fusion Books became the largest yearbook publisher in Australia, proving that the technology worked\u2014but Melanie knew this was just the \u201Cbeta test\u201D for something much bigger.', 'A living room yearbook company became the proving ground for a billion-dollar idea.'),
((SELECT id FROM s3), 2, 'The 100 "No"s', E'In 2011, Melanie flew to San Francisco with a paper pitch deck and a dream. She spent three months sleeping on a friend\u2019s floor, taking trains to every meeting she could get. She was a young woman from Australia in a world dominated by male tech founders.\n\nShe pitched to over 100 venture capitalists. The answer was almost always a polite \u201Cno.\u201D They didn\u2019t think an Australian company could compete with Adobe. They didn\u2019t think \u201Cnon-designers\u201D cared about design. Melanie would go back to her floor-mattress every night, refine her deck based on their feedback, and go back out the next morning. She wasn\u2019t just collecting rejections; she was collecting data on how to make her pitch perfect.', 'She wasn''t collecting rejections—she was collecting data on how to make her pitch perfect.'),
((SELECT id FROM s3), 3, 'The Kiteboarding Connection', E'The turning point came in a place you\u2019d never expect: the ocean. Melanie met Bill Tai, a legendary Silicon Valley investor, at a conference. Bill was obsessed with kiteboarding. He told Melanie that if she wanted him to listen to her pitch, she should come to his kiteboarding retreat, \u201CMaiTai,\u201D in Maui.\n\nMelanie had never kiteboarded in her life. She realized that in the \u201Cboys\u2019 club\u201D of tech, relationships were built on the water. She spent weeks learning to kiteboard, often getting dragged through the waves and bruised, just to get five minutes of Bill\u2019s time on the beach. Her willingness to \u201Crisk it all\u201D in the surf showed Bill that she had the grit to survive the tech world. He eventually became her first major investor and introduced her to the people who would build Canva\u2019s foundation.', 'She learned to kiteboard—getting dragged through waves—just to get five minutes of an investor''s time.'),
((SELECT id FROM s3), 4, 'The Hunt for the "Tech Soul"', E'Even with money promised, Melanie had a massive problem: she didn\u2019t have a Chief Technology Officer (CTO). She spent a year searching for the right engineer to build the \u201Csimple\u201D giant she imagined. She needed someone who could make a complex design engine run in a web browser\u2014something many thought was impossible at the time.\n\nShe eventually found Cameron Adams, a former Google engineer. When she pitched him, she didn\u2019t just show him a business plan; she showed him the five years of success with Fusion Books. She showed him that the \u201Cmarket\u201D was already waiting. Cameron joined as the third co-founder, providing the technical \u201Csoul\u201D to Melanie\u2019s vision.', 'She didn''t just show a business plan—she showed five years of proof that the market was waiting.'),
((SELECT id FROM s3), 5, 'The "One-Year" Secret', E'Before Canva launched to the public in 2013, Melanie kept the product in \u201Cstealth mode\u201D for a year. She was obsessed with the user experience. She didn\u2019t want people to just \u201Cuse\u201D the tool; she wanted them to feel \u201Cempowered\u201D by it.\n\nShe watched \u201Ctest users\u201D try the early version of Canva. If a user hesitated for even two seconds before clicking a button, she would go back to the engineers and tell them to redesign the interface. She realized that people were \u201Cscared\u201D of design. She created an \u201Conboarding\u201D experience that felt like a game, giving users small wins (like changing a color) within the first 30 seconds. By the time they finished the \u201Ctutorial,\u201D they felt like designers.', 'If a user hesitated for even two seconds, she sent the engineers back to redesign.'),
((SELECT id FROM s3), 6, 'The Guy Kawasaki Moment', E'As Canva grew, it caught the attention of Guy Kawasaki, the man who had been Apple\u2019s \u201CChief Evangelist\u201D during the Macintosh era. Guy saw in Canva what he had seen in Apple: a tool that gave power to the people.\n\nHe tweeted about Canva, and the traffic spike nearly crashed their servers. Melanie reached out to him, and soon, Guy became Canva\u2019s Chief Evangelist. Having the man who helped launch Steve Jobs\u2019 legacy join an Australian startup was a massive validation. It told the world that Canva wasn\u2019t just a \u201Csmall tool\u201D\u2014it was a \u201CCategory King.\u201D', 'The man who launched Steve Jobs'' legacy saw in Canva what he saw in Apple.'),
((SELECT id FROM s3), 7, 'Empowering the "Non-Designer"', E'The \u201Chow\u201D of Canva\u2019s explosion was its library of templates. Melanie realized that most people didn\u2019t want to start with a blank white page; they wanted to start with a \u201Cgood idea.\u201D\n\nShe hired a massive team of designers to create thousands of templates for everything from bake-sale flyers to Instagram posts. She made \u201CHigh Design\u201D accessible to the small business owner in India, the teacher in London, and the non-profit in Brazil. Canva became the \u201Csecret weapon\u201D for the Ladyboss who didn\u2019t have the budget for an agency but had the ambition to look professional.', 'Canva became the secret weapon for the Ladyboss who couldn''t afford an agency but had the ambition to look professional.'),
((SELECT id FROM s3), 8, 'Scaling to 190 Countries', E'By 2021, Canva was used in 190 countries and available in over 100 languages. Melanie and Cliff were still at the helm, but they were no longer in a living room. They were leading a team of 2,000 people in a massive, vibrant office in Sydney.\n\nDespite their multi-billion dollar valuation, Melanie kept the culture \u201Cflat.\u201D Every new employee at Canva still goes through the \u201CDesign School\u201D to understand the struggle of the user. She proved that you don\u2019t have to be in Silicon Valley to build a global empire\u2014you just have to solve a problem so deeply that the world can\u2019t imagine living without your solution.', 'You don''t have to be in Silicon Valley—you just have to solve a problem the world can''t live without.'),
((SELECT id FROM s3), 9, 'The "Force for Good"', E'Melanie and Cliff did something rare in the tech world: they pledged to give away the vast majority of their wealth. They launched the \u201CTwo-Step Plan\u201D:\n\n1. Build one of the world\u2019s most valuable companies.\n2. Do the most good they can do.\n\nToday, Melanie Perkins is one of the youngest self-made female billionaires in history, but she still walks into the office with the same \u201CNotice\u201D reflex she had at her mother\u2019s dining table. She proved that a \u201CNo\u201D from 100 investors is just a temporary pause before the \u201CYes\u201D that changes everything.', 'If you get your foot in the door, just keep it there. Eventually, someone will let you in.');

-- Story 4: Lululemon
WITH s4 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'Lululemon: The Yoga Pants Revolution',
    'How one yoga class created a $50 billion empire',
    'This is the story of a man who attended a single yoga class in 1997 and realized that the world was wearing the wrong clothes. It is a story of Vancouver rain, technical fabrics, and a community-led movement that turned "yoga pants" into a $50 billion global religion.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#E2F9F0',
    '🧘',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s4), 0, 'The Cotton Problem', E'In 1997, Chip Wilson was a 42-year-old retail veteran in Vancouver, Canada, who had already built and sold a successful snowboarding brand. He was a man obsessed with technical sports\u2014surfing, skating, and boarding\u2014but his body was starting to feel the years of impact. On a whim, he signed up for a yoga class in a drafty community center.\n\nAs he sat on his mat, he noticed two things: first, that yoga was about to explode in popularity; and second, that everyone was dressed in heavy, baggy cotton. As the room heated up, the cotton became soaked with sweat, grew heavy, and turned see-through. It was a \u201CState of Discomfort.\u201D Chip didn\u2019t see a \u201Cgym class\u201D; he saw a massive engineering failure. He went home that night and decided to apply the high-performance technology of snowboarding gear to the quiet world of the yoga mat.', 'He didn''t see a gym class—he saw a massive engineering failure.'),
((SELECT id FROM s4), 1, 'The Kitsilano Lab', E'In 1998, Chip opened a small space in the Kitsilano neighborhood of Vancouver\u2014a place where the \u201Chippie\u201D past of the city was colliding with a new generation of urban professionals. This wasn\u2019t a store; it was an experiment. By day, it was a design studio where Chip and a small team labored over sewing machines. By night, they cleared the tables and the space became a yoga studio.\n\nThe \u201CHow and Where\u201D was critical: Chip invited the local yoga teachers to use the space for free. In exchange, he asked them for one thing: brutal feedback. He wanted to know where the seams rubbed, where the fabric sagged, and what it felt like to move in his prototypes. The teachers weren\u2019t just \u201Ccustomers\u201D; they were his R&D department. The sound of the sewing machines and the scent of incense defined the early atmosphere of Lululemon.', 'The yoga teachers weren''t customers—they were the R&D department.'),
((SELECT id FROM s4), 2, 'The Birth of "Ocean"', E'While most brands try to sell to everyone, Chip did the opposite. He created a specific, imaginary persona named \u201COcean.\u201D She was a 32-year-old professional woman who earned $100k a year, was fit, traveled, and valued her time. Everything Lululemon did\u2014from the height of the waistband to the scent of the candles in the store\u2014was designed specifically for Ocean. Chip realized that if he could win over \u201COcean,\u201D the rest of the world would follow. He wasn\u2019t just selling pants; he was selling the lifestyle of a woman who had her life together. This precision allowed Lululemon to charge $100 for leggings when the rest of the market was charging $20. It wasn\u2019t about the price; it was about the identity.', 'He wasn''t selling pants—he was selling the lifestyle of a woman who had her life together.'),
((SELECT id FROM s4), 3, 'The Luon Secret', E'The \u201CTechnical Soul\u201D of the brand was a fabric Chip spent years perfecting: Luon. Most athletic fabrics at the time were thin and shiny. Luon was different. It was a nylon-lycra blend that was \u201Cbrushed\u201D to feel like cotton but had the \u201CSelf-Command\u201D of high-performance gear. It was thick enough to provide coverage, but stretchy enough to move through a full Sun Salutation.\n\nIn 2005, Lululemon trademarked Luon, creating a \u201Cmoat\u201D around their product. They built a secret R&D facility called the \u201CWhitespace Lab\u201D in Vancouver. Inside, they used thermal cameras and sweat-trackers to study how the body moves. They weren\u2019t making clothes; they were practicing \u201CThe Science of Feel.\u201D', 'They weren''t making clothes—they were practicing "The Science of Feel."'),
((SELECT id FROM s4), 4, 'The Ambassador Army', E'Chip didn\u2019t have the budget for a Nike-style ad campaign with celebrity athletes. Instead, he created the Ambassador Program. He went to the most popular yoga and fitness instructors in every city and offered them free clothes and a massive photo of themselves on the wall of the local store.\n\nIn exchange, these instructors became the \u201Cpriests\u201D of the brand. When they wore Lululemon to their sold-out classes, their students noticed. It was the ultimate \u201Corganic\u201D marketing. The stores became community hubs, hosting \u201CSunday Morning Yoga\u201D where they cleared the racks to make room for mats. They turned their retail space into a sanctuary.', 'The stores became sanctuaries—they cleared the racks to make room for yoga mats.'),
((SELECT id FROM s4), 5, 'The "Scarcity" Strategy', E'One of the most brilliant parts of the Lululemon \u201CHow\u201D was their inventory system. They intentionally under-produced their most popular items. They created 3-week and 6-week lifecycles for colors and patterns. If you saw a pair of leggings in a specific \u201CSeafoam Green\u201D and didn\u2019t buy them that day, they would be gone by Tuesday. This created a \u201CState of Urgency.\u201D Women didn\u2019t \u201Cbrowse\u201D Lululemon; they \u201Chunted\u201D it. It eliminated the need for sales or discounts, keeping the brand\u2019s premium status intact while ensuring that their \u201Ccommunity\u201D always felt like they were in on a secret.', 'Women didn''t browse Lululemon—they hunted it.'),
((SELECT id FROM s4), 6, 'The IPO and the Global Rush', E'By 2007, the \u201CYoga Craze\u201D had become a global phenomenon, and Lululemon was its undisputed leader. They went public on the NASDAQ, raising over $327 million. The black-and-white \u201CA\u201D logo started appearing on every street corner from SoHo to Sydney.\n\nThey moved beyond yoga, expanding into running, cycling, and swimming. They were the architects of \u201CAthleisure\u201D\u2014the idea that it was socially acceptable (and even stylish) to wear your gym clothes to a business meeting or a brunch. They had successfully changed the \u201CDaily Routine\u201D of the modern woman.', 'They were the architects of "Athleisure"—gym clothes at brunch became not just acceptable, but stylish.'),
((SELECT id FROM s4), 7, 'The See-Through Crisis', E'In 2013, the brand faced its most dangerous moment. A massive batch of the signature black Luon pants arrived in stores, and women quickly realized they were \u201Cunacceptably transparent\u201D when bending over. It was a PR nightmare. Lululemon had to recall 17% of all women\u2019s bottoms.\n\nThe crisis was deepened when Chip Wilson made controversial comments on television, suggesting that \u201Csome women\u2019s bodies just don\u2019t work for the pants.\u201D The backlash was swift. Chip was forced to step down as chairman, and the CEO resigned. The brand was at a crossroads. They had to decide if they were a \u201CFounder-led cult\u201D or a \u201CGlobal institution.\u201D They chose to double down on the \u201CScience of Feel,\u201D hiring new leadership to stabilize the empire.', 'They had to decide: founder-led cult or global institution. They chose the institution.'),
((SELECT id FROM s4), 8, 'Beyond the Mat (Menswear and Mirror)', E'Under new leadership, Lululemon did something many thought impossible: they convinced men to wear the brand. They launched the \u201CABC\u201D (Anti-Ball Crushing) pant, using their technical fabric expertise to solve a comfort problem for men. It became an instant hit, proving that the \u201CLululemon System\u201D wasn\u2019t just for \u201COcean\u201D\u2014it was for \u201CDuke\u201D too.\n\nIn 2020, they made a high-stakes $500 million bet on Mirror, a connected fitness platform. They wanted to be inside the user\u2019s home, not just in their closet. While the acquisition faced many operational hurdles, it showed the brand\u2019s ambition to be a total \u201CLife System,\u201D providing rhythm through digital classes and community connection.', 'They didn''t just want to be in your closet—they wanted to be in your living room.'),
((SELECT id FROM s4), 9, 'The Legacy of the Logo', E'Today, Lululemon is more than a clothing company; it is a case study in Community as Infrastructure. From a single drafty studio in Kitsilano to over 600 stores worldwide, they proved that a brand is not built in a boardroom, but on the mat, through sweat and feedback.\n\nChip Wilson\u2019s original insight\u2014that clothes should work with the human body, not against it\u2014changed an entire industry. They proved that when you build a product that makes a person feel \u201CIn Command\u201D of their physical state, you don\u2019t just build a business; you build a movement.', 'Your clothes are the first environment you live in. If they aren''t right, nothing else will be.');

-- Story 5: Tiffany & Co.
WITH s5 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'Tiffany & Co.: The Blue Box Empire',
    'From $4.98 in sales to the crown jewels of France',
    'This is the story of a man who started with a $1,000 loan and a dream of selling "fancy stationery," only to end up owning the crown jewels of France. It is a story of New York grit, the world''s most famous shade of blue, and a yellow diamond that shines like the sun.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#FFF492',
    '💎',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s5), 0, 'The $4.98 Beginning', E'On September 21, 1837, Lower Manhattan was a hive of muddy streets and horse-drawn carriages. At 259 Broadway, two 25-year-old friends, Charles Lewis Tiffany and John B. Young, nervously opened the doors to their new \u201Cstationery and fancy goods\u201D emporium. They had borrowed $1,000 from Charles\u2019s father, a textile manufacturer, to fill the shelves with Chinese porcelains, French fans, and fine paper.\n\nThe first day was not a triumph. When they tallied the heavy brass cash drawer at closing time, the total sales were exactly $4.98. Most men would have seen that number and felt the weight of a failing dream. But Charles had a secret weapon: he was the first merchant in America to mark every item with a \u201Cnon-negotiable\u201D price tag. No haggling. No favors. This small act of integrity established the brand as a place of absolute trust.', 'First day sales: $4.98. But the principle of non-negotiable integrity would build an empire.'),
((SELECT id FROM s5), 1, 'The Invention of a Color', E'By 1845, the shop was thriving, and Charles decided to launch the first mail-order catalog in American history\u2014the \u201CBlue Book.\u201D For the cover, he chose a specific, vibrant shade of robin\u2019s-egg blue.\n\nHe didn\u2019t choose it because it was trendy; he chose it because turquoise was the favorite stone of the Victorian bride. That blue\u2014later trademarked as Tiffany Blue\u2014became more than a color. It became a psychological trigger. To this day, the sight of a blue box in a woman\u2019s hand causes a physical reaction; it is the universal code for \u201Csomething extraordinary is inside.\u201D', 'A single shade of blue became the universal code for "something extraordinary is inside."'),
((SELECT id FROM s5), 2, 'The King of Diamonds', E'In 1848, a political revolution exploded in France. Aristocrats were fleeing Paris, desperate to trade their family heirlooms for cash. While other jewelers stayed home in fear, Charles Lewis Tiffany did something \u201Creckless.\u201D He risked every penny of his company\u2019s profits to buy a massive cache of diamonds from the fleeing French nobility.\n\nWhen the gems arrived in New York, the American public was stunned. They had never seen diamonds of such quality. The press was so impressed they crowned Charles \u201CThe King of Diamonds.\u201D He had successfully pivoted from a stationery shop to the premier jeweler of the Western world by moving toward a crisis when everyone else was moving away.', 'He moved toward the crisis when everyone else was running away.'),
((SELECT id FROM s5), 3, 'The 128-Carat Sun', E'In 1877, a rough yellow diamond of 287 carats was discovered in a South African mine. Charles bought it for $18,000\u2014a fortune at the time. He didn\u2019t want the biggest diamond; he wanted the most beautiful one.\n\nHe handed the stone to his 23-year-old gemologist, George Frederick Kunz. Kunz spent a year studying the stone before cutting it into a 128.54-carat masterpiece with an unprecedented 82 facets. It was named The Tiffany Diamond. It wasn\u2019t for sale; it was for the world to admire. It became the \u201Csoul\u201D of the brand, a permanent resident of the New York flagship that proved Tiffany valued \u201CBrilliance over Size.\u201D', 'It wasn''t for sale—it was for the world to admire. Brilliance over size.'),
((SELECT id FROM s5), 4, 'The French Crown Jewels', E'Ten years later, in 1887, Charles did the unthinkable. The French government held an auction at the Louvre to sell off the actual French Crown Jewels. Tiffany walked into the heart of Paris and out-bid the royal houses of Europe.\n\nHe bought nearly one-third of the collection, including pieces that had belonged to Empress Eug\u00E9nie. When he brought them back to New York, it changed the status of America forever. It sent a message: the \u201COld World\u201D was fading, and the \u201CNew World\u201D of the entrepreneur was the new royalty.', 'He out-bid the royal houses of Europe—and brought the crown jewels to New York.'),
((SELECT id FROM s5), 5, 'The Six-Prong Revolution', E'Before 1886, diamonds were \u201Cset\u201D deep into the metal of a ring, often hiding their bottom half. It made the stones look dull and heavy. Charles wanted to \u201Cliberate\u201D the diamond. He invented the Tiffany Setting\u2014a six-prong design that lifted the stone off the band and into the light.\n\nIt allowed light to enter the diamond from all sides, creating a \u201Csparkle\u201D that had never been seen before. It was a masterpiece of engineering that redefined the engagement ring forever. Even today, over 130 years later, the \u201CTiffany Setting\u201D is the most imitated piece of jewelry in history, proving that when you lift something into the light, its value multiplies.', 'When you lift something into the light, its value multiplies.'),
((SELECT id FROM s5), 6, 'The Atlas of Fifth Avenue', E'In 1940, Tiffany moved to its legendary home at 57th Street and Fifth Avenue. Above the entrance, Charles placed a 9-foot-tall bronze-coated wooden statue of Atlas clutching a massive clock.\n\nFor generations of New Yorkers, the Atlas clock became the standard for time. People would stop their walk to \u201Creset\u201D their own watches by the Tiffany clock. The building was designed with massive, unobstructed windows to let in the natural New York light\u2014the same light Charles had used to showcase his diamonds since the 1830s.', 'For generations, New Yorkers set their watches by the Tiffany clock.'),
((SELECT id FROM s5), 7, 'The Holly Golightly Effect', E'In 1961, the world\u2019s perception of the brand changed forever with the film Breakfast at Tiffany\u2019s. It was the first time the New York flagship had ever allowed a movie crew inside.\n\nWhen Audrey Hepburn, as Holly Golightly, stepped out of a yellow cab at 6:00 AM to eat a Danish in front of the windows, she wasn\u2019t just \u201Cwindow shopping.\u201D She was seeking a \u201CState of Peace.\u201D As she famously said, \u201CNothing very bad could happen to you there.\u201D The store became a sanctuary, a place where a woman could go to \u201CReset\u201D her mind amidst the chaos of the city.', '"Nothing very bad could happen to you there."'),
((SELECT id FROM s5), 8, 'The Blue Box as a Shield', E'One of the most famous rules at Tiffany & Co. was established by Charles himself: The Blue Box cannot be bought. You can have the most money in the world, but you cannot walk into the store and purchase a box. It must be given to you as a result of a purchase.\n\nThis created a \u201CShield\u201D of exclusivity. The box became a symbol of achievement. Whether it contained a $150 silver key or a $1 million diamond, the box represented the same thing: a standard of excellence.\n\nCharles also standardized the use of \u201C925\u201D for Sterling Silver and established the purity standards for Platinum in the US, ensuring that the system of quality was as strong as the brand.', 'The Blue Box cannot be bought. It must be earned.'),
((SELECT id FROM s5), 9, 'The Landmark and the Legacy', E'In the 2020s, the brand underwent its biggest transformation yet. Now part of the LVMH family, the Fifth Avenue flagship was completely renovated into \u201CThe Landmark.\u201D It features a 10-story high-tech experience, blending the 1837 history with modern digital art.\n\nFrom a $4.98 stationery shop to a $16 billion global icon, Tiffany & Co. proved that longevity is built on resilience. Charles Lewis Tiffany didn\u2019t just sell jewelry; he sold a \u201CState of Aspiration.\u201D He showed that even if you start small, if you hold yourself to a \u201Cnon-negotiable\u201D standard and have the courage to \u201Cbuy the diamonds\u201D during a crisis, you can build a legacy that shines for centuries.', 'A diamond is just a piece of coal that did well under pressure. Your reset is the moment you start to shine.');

-- Story 6: SKIMS
WITH s6 AS (
  INSERT INTO reading_content (title, subtitle, description, author, category, type, theme_color, emoji, cover_aspect, is_published, is_premium)
  VALUES (
    'SKIMS: The Second Skin Revolution',
    'From tea-stained fabrics to a $4 billion empire',
    'This is the story of a woman who spent years in the world''s most famous closets, only to realize that the most basic layer of a woman''s wardrobe was broken. It is a story of tea-stained fabrics in a bathroom sink, a global naming scandal, and a "second skin" that turned a celebrity brand into a $4 billion architectural marvel.',
    'Ladyboss',
    'ladyboss-stories',
    'story',
    '#FFE6C9',
    '👗',
    'square',
    true,
    false
  ) RETURNING id
)
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES
((SELECT id FROM s6), 0, 'The Sink and the Tea Bag', E'Long before she was a billionaire CEO, Kim Kardashian was a woman obsessed with the \u201Carchitecture\u201D of her body. For fifteen years, she was a silent power-user of shapewear, but she had a secret problem: nothing on the market actually matched her skin. Everything was either \u201Cpale beige\u201D or \u201Cdark brown,\u201D with no nuance in between.\n\nIn her multi-million dollar bathroom, she began a DIY laboratory. She would buy existing shapewear and, in a desperate attempt to find the right shade, she would dye the garments in her sink using tea bags and coffee. She would cut and sew pieces together to hide seams under high-slit dresses. She wasn\u2019t just \u201Cgetting ready\u201D; she was performing a daily engineering hack. She realized that if the most famous woman in the world had to use a tea bag to get the right shade of nude, the industry was failing every other woman, too.', 'If she had to use a tea bag to get the right shade, the industry was failing every woman.'),
((SELECT id FROM s6), 1, 'The Meeting of the Minds', E'Kim knew she had the vision, but she needed the \u201Cengine.\u201D She teamed up with Jens and Emma Grede, the entrepreneurial power couple behind other massive brands like Good American. Jens brought the strategic retail mind, and Emma brought a deep commitment to inclusivity.\n\nThey didn\u2019t want to build a \u201Ccelebrity product\u201D that would sit in a discount bin in two years. They wanted to build a \u201CSolution Brand.\u201D They spent two years in development, focusing on \u201CThe Feel.\u201D They hunted for fabrics that could stretch to twice their size but still offer the compression of high-performance shapewear. They were building a tech company that happened to sell underwear.', 'They were building a tech company that happened to sell underwear.'),
((SELECT id FROM s6), 2, 'The "Kimono" Crisis', E'In June 2019, Kim announced the brand\u2019s original name: Kimono. She thought it was a clever pun on her name, but the reaction was an immediate, global crisis. She was accused of cultural appropriation, and even the Mayor of Kyoto, Japan, wrote her a letter asking her to reconsider.\n\nThis was a high-stakes moment. Most brands would have doubled down or disappeared in shame. Kim spent a few days in silence, listening. She realized her mistake wasn\u2019t just a PR problem; it was a values problem. She threw away $10 million worth of pre-printed packaging and labels. She pushed the launch back two months and emerged with a new name: SKIMS. It was a reset that cost a fortune but saved the soul of the brand.', 'She threw away $10 million in packaging. The reset cost a fortune but saved the soul of the brand.'),
((SELECT id FROM s6), 3, 'The Digital Stampede', E'September 10, 2019, was the day the \u201COld World\u201D of retail died a little more. When the SKIMS website finally went live, the traffic was so explosive that the servers struggled to breathe. In the first few minutes, the brand did $2 million in sales.\n\nWomen weren\u2019t just buying one bra; they were buying entire \u201Ckits.\u201D They were buying into the idea that they didn\u2019t have to \u201Cfight\u201D their clothes anymore. The \u201CFits Everybody\u201D collection became an instant legend. Kim didn\u2019t use professional models for the launch; she used real women of all shapes, proving that the Ladyboss looks like everyone.', '$2 million in the first few minutes. Women weren''t buying bras—they were buying freedom from fighting their clothes.'),
((SELECT id FROM s6), 4, 'The Fabric Secret', E'The \u201CHow\u201D of SKIMS lies in the knitting. Most shapewear feels like a \u201Ccage\u201D\u2014it\u2019s stiff and restrictive. SKIMS invested in high-tech Italian knitting machines that could create \u201Czonal compression.\u201D This meant a single garment could be tight in the waist but soft and stretchy in the chest. They created nine specific shades of \u201Cnude,\u201D covering a spectrum that the industry had ignored for decades. They didn\u2019t just add a \u201Cplus size\u201D section; they designed every piece from XXS to 4X from the ground up. This technical obsession turned the product from a \u201Chassle\u201D into a \u201Csecond skin\u201D that women actually wanted to wear all day.', 'Nine shades of nude. Every piece designed from XXS to 4X from the ground up.'),
((SELECT id FROM s6), 5, 'The Olympic Gold', E'In 2021, SKIMS achieved a level of validation that most brands wait decades for. They were named the official underwear and loungewear sponsor for Team USA at the Tokyo Olympics and Paralympics. Seeing the world\u2019s greatest athletes\u2014women who represent the peak of human performance\u2014wearing SKIMS in the Olympic Village changed the narrative. It wasn\u2019t just about \u201Clooking good\u201D for a red carpet anymore; it was about \u201Cfunctioning\u201D for the elite. It turned the brand from a celebrity \u201Cside hustle\u201D into a global infrastructure for the female body.', 'Olympic athletes wearing SKIMS turned a celebrity brand into global infrastructure for the female body.'),
((SELECT id FROM s6), 6, 'The "Drop" Mastery', E'SKIMS perfected the art of the \u201CDrop\u201D model. They don\u2019t just \u201Cstock\u201D products; they create \u201Cevents.\u201D Every Tuesday, a new limited-edition color or style is teased to Kim\u2019s 360 million followers. By the time the clock hits 9:00 AM PT, hundreds of thousands of women are waiting with their credit cards ready. By 9:05 AM, most of it is gone. This \u201CScarcity Strategy\u201D creates a culture of \u201CThe Hunt.\u201D It keeps the brand fresh, addictive, and constantly in the social media conversation. It\u2019s a routine that their customers look forward to every week.', 'By 9:05 AM, most of it is gone. Women don''t shop SKIMS—they hunt it.'),
((SELECT id FROM s6), 7, 'The Adaptive Revolution', E'In 2022, SKIMS did something that few \u201Ccool\u201D brands have the courage to do. They launched the Adaptive Collection. They worked with people with limited mobility to design underwear with subtle hook-and-eye closures on the sides, making it easier to put on and take off for those with disabilities or chronic pain.\n\nThey proved that \u201CInclusivity\u201D wasn\u2019t just a marketing word\u2014it was a design requirement. They made adaptive fashion look sleek and sexy, removing the \u201Cmedical\u201D feel that usually accompanies such products. It was a moment of pure empowerment for a community that the fashion world usually leaves behind.', 'Inclusivity wasn''t a marketing word—it was a design requirement.'),
((SELECT id FROM s6), 8, 'The Menswear Pivot', E'In 2023, SKIMS did the unthinkable: they launched a men\u2019s line. To make it \u201Cwork,\u201D they didn\u2019t lead with Kim; they led with icons of grit and performance. They tapped Neymar Jr., Nick Bosa, and Shai Gilgeous-Alexander.\n\nThe launch was so successful that it crashed the website again. They realized that men, too, were tired of \u201Cboring\u201D underwear that didn\u2019t fit or breathe. By applying their fabric technology to the male market, they proved that the \u201CSKIMS System\u201D was universal. They had successfully built a \u201CHuman\u201D brand, not just a \u201CWoman\u2019s\u201D brand.', 'They didn''t build a women''s brand—they built a human brand.'),
((SELECT id FROM s6), 9, 'The $4 Billion Legacy', E'By 2024, SKIMS reached a valuation of $4 billion. Kim Kardashian had successfully moved from being the \u201Cproduct\u201D to being the \u201CArchitect.\u201D She proved that you can take the frustration of not finding your shade and turn it into the foundation of a global empire.\n\nThe story of SKIMS is simple: it started in a sink with a tea bag, and it ended up in the permanent collection of modern culture. It serves as a reminder to every Ladyboss that your frustrations are often the blueprints for your greatest successes.', 'Success isn''t about fitting into the world''s standards. It''s about redesigning the world so that it finally fits you.');
