
-- Delete existing sections for Courageous Character
DELETE FROM reading_sections WHERE content_id = 'c2b3d4e5-f6a7-8901-bcde-f12345678901';

-- Update reading time
UPDATE reading_content SET reading_time_minutes = 30 WHERE id = 'c2b3d4e5-f6a7-8901-bcde-f12345678901';

-- Insert complete sections
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote, image_url) VALUES

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 0, 'Introduction',
E'"Ms. Mirzaei, what if my family or those around me can''t handle the change in my behavior, and embracing a Courageous Character makes me lose them?"\n\nHello Ladyboss! I''m Razieh Mirzaei, the author of Courageous Character. If this question is the last obstacle stopping you from reading this book, I''m dedicating this introduction entirely to this topic.\n\nWhen I first started on this path, I had the same worry. I was afraid, but I moved forward. Later, I realized that belief was fundamentally wrong. These days you hear things like "The winner ends up alone" or "If you grow, those around you will be left behind" — but all of these are lies. People say these things to frighten you and stop you from progressing.\n\nWhat we''ve seen is exactly the opposite. The content of this book is distilled from our Courageous Character workshops with over 15,000 participants. Out of every 10 people who experienced personal growth, 9 of them inspired change in those around them. Trust that when you take steps forward, your loved ones will also wake up and join you.\n\nThe single most important point is: until your Courageous Character is fully developed, you don''t need to broadcast what you''re learning. A Ladyboss shows results through actions and outcomes, not words. First, in complete silence, read the book to the end and do the exercises. Very soon, the people around you will come to you on their own and ask, "What have you been doing?"\n\nToday I have my family and loved ones by my side. My younger sister joined me three years ago and has become one of the main managers of the Ladyboss Academy. She used to be a quiet college girl, but today I entrust her with our most important meetings.',
'When you become a better version of yourself, those around you will start moving forward too.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 1, 'Chapter One: All the Courage in the World',
E'Welcome to Chapter One of Courageous Character. In this chapter I want to teach you the path to becoming a courageous woman: how to leave shyness behind and boost your confidence in communication.\n\nI am Razieh Mirzaei, the founder of Ladyboss Academy. In the past three years, through running Courageous Character workshops, I''ve helped many women become courageous.\n\nI want to start with a very important question: If you had all the courage in the world right now, what would you do?\n\nWhen I asked this in workshops, one student answered, "I''d go to my boss and ask, What happened to that promotion you promised me six months ago?" Another said, "I''d sit down with my husband and tell him our relationship isn''t like it used to be." And another said, "I''d start filming myself and posting content—because I want to build a page with millions of followers."\n\nNow it''s your turn: If you had all the courage in the world, what would you do? Take 30 seconds, give yourself a moment, and write down your answer.',
'If you had all the courage in the world right now, what would you do?', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 2, 'How Did You Dare?',
E'Ladies, when I became a business coach for women, this field was dominated by men. The entire market was taken by men with fancy offices, wearing Rolexes and expensive suits. A girl from out of town, dressed simply and taking taxis, had no place there. But I achieved results for my clients that many of those men hadn''t.\n\nI was a girl from the traditional culture of the south of Iran. But I was very hopeful and driven to improve myself. I realized I needed to become independent, so I went to Tehran for graduate school. My family strongly opposed the idea.\n\nWithin less than seven months of arriving in Tehran, I realized that the 9-to-5 working life was not what I wanted. So I quit. I started selling insurance—a job with no salary or guaranteed income. When my family found out, they withdrew their support—both financial and emotional.\n\nI had no income, no support; I didn''t know anyone in Tehran. The first thing I did was acquire various skills—website design, content creation, Instagram marketing, business coaching. Over six years, my business grew bigger and more successful. Now I live in Istanbul, and the Ladyboss Academy has officially registered an international branch in Toronto, Canada.\n\nBut if I had remained the same Razieh I was back in 2013–2014, none of these events would have happened. So what changed?',
NULL, NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 3, 'The Roots of Timidity',
E'I realized I was shy. In simple terms, I lacked courage, and it was stunting my growth. I needed to learn more about shyness so I could get it under control.\n\nLet me ask you two questions:\n\nFirst: How many times have you avoided going after an opportunity you knew you could do well, simply because you didn''t have the courage—only to see someone else step in and make great progress?\n\nSecond: How many times have you had an amazing idea, but at the first sign of someone else''s opinion, you dropped it and walked away?\n\nIf you''ve had experiences like these, it means you too need to let go of timidity. In my research, I discovered several external roots of timidity—hearing snide remarks, being mocked, the excessive politeness ingrained in our culture. But even in the same society, I saw many women who are truly courageous. I concluded that there is an even more important internal root.',
NULL, NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 4, 'The Story of Two Brains',
E'In simple terms, we have two brains. Our first brain is the old brain, located at the back of our head. It exists in all reptiles, which is why they call it the "reptilian brain." It''s very simple—its job is to keep us alive, and it really only knows two things: run away or attack.\n\nAt the front of your head, there''s the new brain. This brain is trainable and learns to do things other than fight or flight. Early humans learned they don''t always have to flee; they can climb a tree or pick up a torch to scare animals off.\n\nIn today''s world, our old brain''s reactions have been replaced: instead of fleeing, it feels shyness; instead of attacking, it shows aggression.\n\nOur new brain can be trained. If you feel sleepy, your old brain says "go to sleep." But the new brain says, "I can drink some coffee so I won''t miss this important training." The new brain always checks first if it has a relevant "file" stored from your experiences. If it finds nothing, it falls back on the old brain''s method.\n\nSo the first root of shyness: we don''t have the right files in our brain to show us how to behave courageously. When our new brain finds no such file, it resorts to the old brain—we escape, we shrink away.',
'The first root of shyness is that we don''t have the right files in our brain to show us how to behave correctly in a courageous way.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 5, 'The Story of the Corner of the Brain',
E'The second root of timidity lies in a corner of your brain that connects experiences to emotions.\n\nAs a child you touched a knife, cut your hand, and it hurt. Now whenever you see a knife, you pull away—because previously it caused you pain. From that point on, you stored: "Knife = Pain."\n\nSimilarly, as a child you may have shared a funny story in front of people and were scolded for it. In that corner of your brain, you stored: "Being in a group = Pain." Or you asserted your right in a simple situation and the other person reacted badly—you stored: "Standing up for myself = Pain."\n\nWhen certain social situations become equated with pain, that corner of your brain sounds an alarm. Your heart starts to race, your face turns red, stress hormones flood in and cut off your access to long-term memory. We commonly call this state "blanking out."\n\nNothing comes to mind. Your tongue gets tied. Then hours later, it suddenly occurs to you what you should have said. Your level of alertness drops, and you revert to behaving almost like a four-year-old child.\n\nWhenever you feel you''re about to speak up, that corner of your brain tries to stop you. It says, "No—avoid it, run away." You stop putting yourself forward, you say, "Forget it, it''ll just cause trouble." And that is the second root of shyness.',
'Whenever you feel you''re about to ask for something or speak up, that corner of your brain tries to stop you.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 6, 'Chapter Two: The Triple Opinion Technique',
E'Welcome to Chapter Two of Courageous Character. In this chapter we''re going to see what shyness does to you. The more you become aware of the harms of timidity, the more inclined you''ll be to become courageous.\n\nBut first, I want to teach you an extremely practical technique for expressing your opinions powerfully.\n\nOne of the major signs of timidity is that we don''t express ourselves. Many of you are afraid to say what''s on your mind. Here''s a very typical scenario: in a group discussion, you have a different opinion, but you just agree with everyone else and keep your opinion to yourself.\n\nThe Triple Opinion Technique will help you express your opinion effectively:\n\nFact #1 → Fact #2 → Your Opinion\n\nBy "fact," I mean something everyone would agree is true. By "opinion," I mean your personal viewpoint. For example, if someone asks about pursuing graduate studies abroad and you want to agree:\n\n"First, studying abroad is generally a great move and helps people grow. Second, right now many people are leaving to continue their education. So my suggestion is: go for it."\n\nBy structuring your responses this way—two facts that everyone accepts, followed by your opinion—you come across as thoughtful and persuasive rather than impulsive. Practice this formula whenever you want to express a different opinion.',
'Fact #1 → Fact #2 → Your Opinion. The Triple Opinion Technique helps you present your views in a calm, confident, and convincing manner.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 7, 'The Financial Harms of Timidity',
E'Now let''s look at what shyness truly costs you. I''m going to ask you 12 questions about the financial harm timidity might have caused in your life:\n\n1. Has someone borrowed something from you and not returned it?\n2. Have relatives come to you for help but never paid you for your work?\n3. Were you unable to ask for the pay or salary you expected?\n4. Have you failed to put an agreement in writing, and someone denied what they owed you?\n5. Have you invested in a one-sided relationship without reciprocation?\n6. Did you miss out on an opportunity because you were too shy to ask questions?\n7. Have you paid more than your fair share in group expenses?\n8. In negotiations, have you often yielded too easily—buying something you didn''t want because you felt bad?\n9. Have you signed a bad deal because you couldn''t say no?\n10. Have you kept your skills hidden, only to watch someone else present that same idea and reap the benefits?\n11. Have you failed to pursue a professional opportunity because of shyness?\n12. Because of excessive courtesy, have you made yourself ill and had to spend money on treatment?\n\nWhatever your score, write it down. For each situation that happened to you, you''ve seen how shyness cost you money.',
NULL, NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 8, 'Building Communication Files',
E'The next step in becoming a courageous woman is to build up your "communication files"—the set of responses and skills that a courageous woman needs in social situations. Here are six essential ones:\n\n1. Saying No\n2. Claiming Your Rights\n3. Receiving Criticism (without being shaken)\n4. Dropping Excessive Politeness (not being a people-pleaser at your own expense)\n5. Expressing Opinions\n6. Making Effective Requests\n\nThese are the six "files" you must develop. You need to devote time to each and practice them. In this book, I will thoroughly teach you techniques for each one.\n\nOne of the most powerful techniques to start fixing the root of shyness is the Harm Exercise—the questionnaire you just did. By constantly reminding that corner of your brain how much you''ve been hurt by timidity, you gradually realize that being a courageous woman doesn''t hurt at all—on the contrary, it''s being a timid woman that causes pain and suffering.\n\nAs I mentioned, in order to leave shyness behind, you need to do two things:\n1. Change the Roots – Uproot the deep causes of your timidity\n2. Learn the Skills – Build those communication "files"\n\nThat''s why our book is divided into two parts. In the first 5 chapters, we work on the roots. In the second 5 chapters, you''ll learn the communication techniques.',
'Being a courageous woman doesn''t hurt at all—on the contrary, it''s being a timid woman that causes pain and suffering.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 9, 'Chapter Three: Cultivating Courageous Habits',
E'Welcome to Chapter Three. In this chapter, I want to teach you how to cultivate the habits of courageous women, so that in different situations you automatically and comfortably behave like a courageous woman.\n\nLook at two women side by side. The courageous one holds her head high, smiles, looks straight ahead, her shoulders are relaxed back, her spine is straight. The timid one has her head down, chin tucked in, shoulders slumped and hunched forward, arms crossed over her body.\n\nIt''s very clear that our body posture affects others'' perception of us. But an even more important fact is that our inner state is not separate from our body language—our inner feelings directly affect our outward posture.\n\nIf you''re spending a lot of your day slouching, head down, curled up in yourself, chances are you''re either timid or feeling upset. If you transform into a courageous woman, it will absolutely show in your appearance.\n\nBut here''s something even more important: Does our body posture influence our inner state? Research says yes!',
'If you transform into a courageous woman, it will absolutely show in your appearance.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 10, 'The $50 Gamble Experiment',
E'Researchers gathered two groups. They told the first group to strike powerful, victorious poses—lift your shoulders, spread your arms, raise your hands up, head held high. They told the second group to do the opposite—frown, hang your head down, sit with arms crossed and back bent.\n\nThey had both groups hold these poses for a few minutes. Then they gave each person a $50 windfall and said: "There''s a 50% chance your $50 will double to $100, and a 50% chance you''ll lose it."\n\nMany of those who had been holding the confident power poses said, "Yes, we want to take the risk." Their courage had increased! Those in the timid poses were much less inclined. Most said, "No, just give us the $50."\n\nWhat was fascinating was that many people behaved in ways opposite to their usual habits. Some in the "timid pose" group said, "We''re usually the gambling type, but we don''t know why we didn''t feel like taking the risk." In the confident-pose group, people said, "We''ve never been ones to gamble, but now we wanted to do it."\n\nSo if you take a victory pose before an important meeting, you''ll see the effect on your confidence. Step into a private space and strike a power pose for a few minutes. This technique truly makes you feel braver.',
'Your outward posture directly affects your inner state.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 11, 'Eye Contact & Smile',
E'When it comes to body language, there are two habits you must develop to become a courageous woman:\n\n1. Eye Contact\nTimid women aren''t used to making eye contact. But when someone speaks with you, as a courageous woman you should meet their gaze. By looking them in the eye, you show that the person is important to you. In any conversation—whether making a request or standing up for yourself—maintaining eye contact makes you appear more confident and respectful. It''s precisely when you''re under pressure that you need to force yourself to look up and meet the other person''s eyes.\n\n2. Smile\nThe most valuable gift you can give someone—which costs absolutely nothing—is your smile. Even in professional discussions, having a smile shows how composed you are. Even in a stressful scenario, a smile signals to the other party that you are not intimidated. Keeping a smile actually feeds back into your inner state, making you feel more empowered.\n\nYou might ask: "What if I''m just not used to these things?" I remember being at the beginning of this journey myself. When I''d face a stranger, I''d forget every skill I knew. One of my funniest memories: when I first started holding online classes, I''d remind myself to look at the camera—but as soon as the class began, I''d forget and stare at the bottom of the chat window the whole time!\n\nThe key is to practice in safe situations, use reminders, and gradually challenge yourself. With consistent practice, these behaviors will become second nature.',
'The most valuable gift you can give someone—which costs absolutely nothing—is your smile.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 12, 'Chapter Four: Healthy Assertiveness',
E'Welcome to Chapter Four. Reaching this chapter is an achievement in itself, since so many people give up earlier—so congratulations on persevering!\n\nSelf-expression is the pearl in the shell of your confidence. In the same way a diver works hard at the ocean floor to find a pearl inside a shell, you have to work on your self-confidence to find the inner power of self-expression.\n\nSelf-expression means asserting your rights and articulating your thoughts, feelings, and beliefs in an effective, direct, and honest way.\n\nSome people do speak their mind, but in a way that the other person feels attacked—that''s aggressive self-expression. On the opposite end, some people never express what''s inside them at all—that''s passive self-expression.\n\nWhat we aim for is assertive behavior—the kind of self-expression that helps you achieve your desired outcome without trampling on the rights of others.',
'Self-expression is the pearl in the shell of your confidence.', NULL),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 13, 'The Ideal Behavior of a Courageous Woman',
E'The ideal behavior we''re aiming for has three characteristics:\n\nFirst: Your self-expression should be assertive—meaning you do voice your wants, feelings, and beliefs openly.\n\nSecond: Your self-expression should be respectful—meaning you regard both yourself and the other person as worthy of respect. In many interactions, you''ll see people who respect themselves but not the other person. A courageous Ladyboss believes that all human beings are worthy of respect.\n\nThird: Your self-expression should be effective—meaning it actually achieves the result you''re looking for, without causing unnecessary conflict or hurt.\n\nEven if someone makes a mistake—yes, even a serious mistake—there are proper channels to address that person''s wrongdoing. But you, as a courageous woman, never allow yourself to insult someone or pass personal judgment.\n\nThere''s a test designed by Dr. Rathus with 30 questions to measure your assertiveness. Take the test to see your current score—then take it again in two weeks or a month after practicing the exercises in this book to see how your score improves.\n\nThe questions are drawn directly from everyday life, because the ordinary behaviors we exhibit determine whether, in a critical moment, we''ll be able to handle the situation or not.\n\nLadies, you now have the complete foundation for your Courageous Character journey. The first four chapters gave you the roots—understanding timidity, seeing its harms, cultivating courageous habits, and learning assertive self-expression. Now it''s time to put these into practice, step by step, every single day.',
'A courageous Ladyboss believes that all human beings are worthy of respect.', NULL);
