
-- Update reading time to reflect full book
UPDATE reading_content SET reading_time_minutes = 60 WHERE id = 'c2b3d4e5-f6a7-8901-bcde-f12345678901';

-- Insert chapters 5-10 sections
INSERT INTO reading_sections (content_id, sort_order, heading, body, quote) VALUES

-- Chapter 5: Finishing the Roots
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 14, 'Chapter Five: Finishing the Roots', E'Congratulations — you have completed the first half of the book! In this chapter, we finish the topic of changing the roots of timidity and prepare to learn practical courage techniques.\n\nI want to ask you a powerful question: If resentment and regret were completely eliminated from your life, how would you feel?\n\nRegret is when you didn''t voice something you wanted, and so you lost out on it. Resentment is when you had a right, but you didn''t claim it and ended up losing it.\n\nPicture that by the time you finish this book, you have learned to say no perfectly. When you tell someone "no," it causes no trouble for you at all — and not only does the other person not get upset, your relationship might even improve because of the clarity.\n\nImagine that you are completely adept at preventing your rights from being trampled. A person with these skills no longer carries resentment, no longer harbors lasting regrets.', E'If resentment and regret were completely eliminated from your life, how would you feel?'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 15, 'Find Your One Special Insight', E'I want to share a learning approach that made a world of difference for me. I''ve invested heavily in my own education over the years. I noticed something important: a lot of people attend various courses and read many books, yet nothing changes in their lives.\n\nThe problem lies in how people learn. We were trained in school to memorize tons of new things — which usually didn''t translate into real change.\n\nI learned that when I join a new course or read a book, I''m not there to collect a thousand new points. I''m there to find that one key point that can create a change in my life today.\n\nImagine you go to a class and learn 1,000 interesting facts. How many can you realistically implement? Probably none, if you try all at once. But if you learn just one thing you can immediately use to change something — that is incredibly valuable.\n\nFor many of you, that very special nugget might be the Triple Opinion Technique. For others, perhaps a different tip struck a chord. Find that one very special insight for you — and carry it forward into your life.', E'I''m there to find that one key point that can create a change in my life today.'),

-- Chapter 6: Saying No
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 16, 'Chapter Six: A Ladyboss''s "No"', E'Welcome to the second half of the book! This is where we dive into hands-on techniques. We''re starting with a big one: Saying "No."\n\nThe ability to say no — to turn down requests or demands that are not right for you — is absolutely critical for a confident, empowered life. Every courageous woman masters this skill.\n\nWhat happens when we don''t say no? A huge source of stress, resentment, and even financial or emotional loss for timid women is the inability to refuse things they don''t want.\n\nLearning to say no is not about being rude or selfish — it''s about setting healthy boundaries for yourself while still being respectful to others.', E'Learning to say no is not about being rude or selfish — it''s about setting healthy boundaries.'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 17, 'The Six-Step "No" Formula', E'Here is the Ladyboss No formula:\n\nStep 1: Start with a Personal Acknowledgment — Say Their Name. Hearing one''s name is inherently disarming and friendly.\n\nStep 2: Use a Polite Lead-in ("Can I ask…") and State Your Request. Phrasing it gently as a question shows respect while introducing what you need.\n\nStep 3: Give a Brief Honest Reason. You don''t owe long explanations, but a short genuine reason helps the other person understand.\n\nStep 4: Offer an Alternative or Appreciation. Show that you value the person''s needs even though you''re declining.\n\nStep 5: Give Them a Choice and Thank Them. Frame it as a choice rather than a flat refusal.\n\nStep 6: If They Push, Stick to Your "No" Calmly. Repeat your stance politely but firmly, without getting drawn into lengthy justification.\n\nBy structuring your "no" this way, you are being assertive (clearly declining), respectful (polite, using name, appreciating the ask), and fair (offering alternatives or context).', E'A well-delivered no might disappoint someone momentarily, but it ultimately earns their respect.'),

-- Chapter 7: Standing Up for Your Rights
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 18, 'Chapter Seven: Preventing Your Rights from Being Trampled', E'Now that you''ve learned how to say "No," the next skill is closely related: standing up for your rights.\n\nMany shy women let others overstep their boundaries — whether it''s not being paid what you''re owed, being treated unfairly, or having your needs ignored — because they feel unable to assert themselves. That ends here.\n\nStep 1: Choose the Right Channel. Should you talk in person? Is a phone call sufficient? A written email? Or even legal action?\n\nStep 2: Plan What You''ll Say. Clarity is key. You don''t need to rant or get emotional — firmly and politely state what you''re owed or what you expect, and by when.\n\nStep 3: Maintain Composure. Use confident body language and a steady voice. Practice beforehand if needed.\n\nStep 4: Be Persistent but Polite. If one ask isn''t enough, follow up without losing your cool.\n\nStep 5: Address Issues Early. The earlier you bring up a boundary issue, the easier it usually is to resolve.\n\nStep 6: Know Your Line and Be Ready to Enforce It. A courageous woman values herself enough to take stronger action if someone persistently violates her rights.', E'Confronting does not mean fighting. It can be done calmly and wisely.'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 19, 'Use "I" Statements, Not Attacks', E'In all these examples, use "I" statements and don''t attack the other person. Express your need or observation without calling them names or assuming their intentions.\n\nInstead of: "You''re all lazy and incompetent!" — try: "I hired your company to complete X by this date. We''re now a week past and the work isn''t done as agreed. This is causing me problems. I need to know how you will fix this."\n\nSee the difference? You''re pointing out the breach and firmly asking for a solution, not hurling insults.\n\nEarly in my career, a client delayed payment forever. Younger me was anxious about pressing too hard. But I finally realized: I had delivered my work, and it was my right to be paid. I professionally but firmly told them I needed payment by a specific date or I''d have to cease work.\n\nGuess what? They paid. And I learned that being assertive doesn''t ruin professional relationships — lack of assertiveness and resulting resentment does.', E'Being assertive doesn''t ruin professional relationships — lack of assertiveness and resulting resentment does.'),

-- Chapter 8: Making Requests
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 20, 'Chapter Eight: Making Effective Requests', E'In this chapter, I''ll teach you how to make effective requests — asking for what you want or need in a way that significantly increases the chance of a positive response.\n\nMany of us either hesitate to ask at all (expecting others to read our minds), or we ask in a roundabout, ineffective way. A courageous woman knows how to ask clearly and assertively, while still being respectful.\n\nHere''s my formula:\nName + Could You [do X] + Context + Thanks\n\nExample: "Ms. Lee, could I discuss our project budget? We''ve run the numbers and need an additional $5,000 to meet targets. Would you approve that? Thank you for considering this."\n\nNotice: I used her name, stated the request clearly, gave context, and ended with appreciation. This is succinct, respectful, and clear.\n\nA common mistake is over-explaining or apologizing too much: "I''m so sorry to ask, you''re probably very busy…" This dilutes your message and can actually make it easy to say no. Instead, be succinct and acknowledge their effort with thanks — but don''t over-apologize for asking.', E'Closed mouths don''t get fed. A Ladyboss speaks up for her needs while respecting others.'),

-- Chapter 9: Handling Criticism
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 21, 'Chapter Nine: Overcoming Mockery and Criticism', E'In this chapter, we tackle how to handle mockery and criticism without losing confidence.\n\nAn important mindset: No one can make you feel inferior without your consent.\n\nLet''s break criticism into two categories:\n• Constructive criticism — useful feedback, even if blunt.\n• Mockery or malicious criticism — meant to hurt or belittle.\n\nFor mockery, here are your strategies:\n\nStrategy 1: Respond with Confidence. They say "Don''t make me laugh," you smile calmly and reply, "Watch me surprise you." Short, unfazed, and positive.\n\nStrategy 2: Call it Out Respectfully. "I''ve noticed you often make jokes about my goals. I take them seriously. I''d appreciate your support — or at least not your ridicule."\n\nStrategy 3: Ignore and Excel. The best revenge is massive success. Use mockery as fuel. Focus and do exactly what they said you couldn''t.\n\nFor constructive criticism: Listen for the kernel of truth. Don''t take it personally — "This report is a mess" doesn''t mean "you are a mess." And owning mistakes is actually a show of strength.', E'No one can make you feel inferior without your consent.'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 22, 'The "Fogging" Technique', E'Sometimes humor helps defuse criticism. One technique is called "fogging" — you acknowledge any truth in the insult in a neutral way that diffuses it.\n\nExample: Someone says "You talk too much in meetings." You chuckle and reply, "You might be right — I do have a lot to say!" Then optionally add something constructive: "I''ll try to make sure others get to speak too."\n\nAnother example: If someone says "You''ll never get that promotion," you might smile and say "Maybe, but it sure will be fun proving you wrong!" The key is showing confidence without hostility.\n\nAlso crucial: Surround yourself with positivity elsewhere. We can''t always avoid negative people, but we can ensure we have a support system. Their encouragement acts as a buffer against negativity.\n\nAnd remember: no one has the right to disrespect you. If mockery crosses the line into abuse or harassment, courage isn''t enduring it silently — it''s knowing you deserve respect and taking action to secure it.', E'The best revenge is massive success.'),

-- Chapter 10: Maximum Confidence
('c2b3d4e5-f6a7-8901-bcde-f12345678901', 23, 'Chapter Ten: The Eagle Story', E'Welcome to our final chapter. Let me share a story that greatly influenced me — the story of the eagle chick.\n\nOnce upon a time, high on a mountainside, an eagle laid an egg. During a storm, the egg fell and ended up in a farmyard among the hen''s eggs. A mother hen kept the strange egg warm until it hatched.\n\nThe baby eagle found itself surrounded by chickens. It did what chicks did — pecking at the ground, fluttering but never really flying. But at night, the young eagle felt restless, gazing at the sky, somehow drawn to the open air.\n\nOne day, the young eagle saw several eagles soaring high above. Something snapped awake. The chickens shouted: "You''re one of us. You can''t fly! Who do you think you are?"\n\nNow the eagle stood at a life crossroads: listen to the chickens — the voices saying "You can''t, don''t try, be ordinary" — or listen to that burning inner feeling that it was meant for the skies.\n\nDear reader, you are that eagle. The fact that you read this book to the end tells me you have a courageous spirit eager to soar. You absolutely can fly.', E'You are that eagle. The fact that you read this book tells me you have a courageous spirit eager to soar.'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 24, 'Three Secrets to Maximum Confidence', E'How do you reach maximum confidence? I have 3 secrets that transformed my life.\n\nSecret #1: Embrace Discomfort — It''s Your Growth Zone.\nWhen something challenges you and makes your heart race, see it as a sign you are about to grow. The discomfort is temporary, but the confidence you gain is permanent. Train yourself: if it scares me a little, that means I should do it.\n\nSecret #2: Reflect on Your Wins — Nourish Your Confidence.\nConfidence is like a fire — you have to keep fueling it. That fuel comes from remembering and celebrating what you''ve achieved. Keep a "success journal." Write down anything you''re pleased about — even small wins. They pile up into deep confidence.\n\nSecret #3: Act As If — Step into the Ladyboss Version of You.\nEven when you don''t totally feel confident, act as if you are. This is not being fake — it''s practicing the behaviors of confidence until they become real. I literally used to practice power poses in private. I created an alter ego — a superhero version of myself. Over time, those behaviors merged with the real me, and I BECAME her.\n\nBy applying these three secrets consistently, you reach a level of self-confidence where everything opens up.', E'Confidence is like a fire — you have to keep fueling it.'),

('c2b3d4e5-f6a7-8901-bcde-f12345678901', 25, 'Fly High, Dear Ladyboss', E'Whenever people ask me, "What was the key that got you where you are?" I answer: I thrived on confidence. Confidence has been my sustenance and main tool.\n\nImagine: you trust yourself completely. You know that even if something goes wrong, you can handle it. You walk into new situations excited rather than fearful. You see opportunities where you used to see obstacles.\n\nA few years after building my confidence, one of my biggest business deals was falling through. The old me would have panicked. The new confident me calmly re-strategized, contacted a different partner, saved the deal, and even improved it. Confidence had given me not just courage, but clarity under pressure.\n\nThis isn''t really an end — it''s a commencement. The start of a new chapter where you live as a Courageous Character, a true Ladyboss.\n\nYou have everything it takes to achieve your dreams and lift others up with you. I am cheering for you every step of the way.\n\nFly high, dear Ladyboss, and never doubt for a second that the sky is your domain.\n\nWith all my love and confidence in you,\nRazieh Mirzaei', E'Fly high, dear Ladyboss, and never doubt for a second that the sky is your domain.');
