
UPDATE reflections SET emoji = CASE title
  -- Deep Dives
  WHEN 'Practice Gratitue' THEN '🙏'
  WHEN 'Self-Affirmation' THEN '💪'
  WHEN 'Pure Reflection' THEN '🪞'
  WHEN 'When You Feel Lonely' THEN '🫂'
  WHEN 'When You Feel Anxious' THEN '😰'
  WHEN 'When You Feel Sad' THEN '😢'
  WHEN 'When You Want to Overeat' THEN '🍽️'
  WHEN 'When You Abuse Alcohol' THEN '🍷'
  WHEN 'When Work Makes You Angry' THEN '😤'
  WHEN 'You Need to Communicate' THEN '💬'
  WHEN 'Travel Diary' THEN '✈️'
  WHEN 'Happy Diary' THEN '😊'
  WHEN 'Savoring Pleasant Moments' THEN '🌸'
  WHEN 'What Would You Say to a Loved One?' THEN '💌'
  WHEN 'Managing Your Triggers' THEN '🎯'
  -- Morning
  WHEN 'Morning Reflection' THEN '🌅'
  WHEN 'Sleep Reflection' THEN '😴'
  WHEN 'Hype Machine' THEN '🔥'
  WHEN 'Meal Time' THEN '🥗'
  WHEN 'Confidence Booster' THEN '🦁'
  WHEN 'Gratitude Jar' THEN '🫙'
  WHEN 'Affirmation of the Day' THEN '✨'
  WHEN 'Happiness Magnifier' THEN '🔍'
  WHEN 'Dream Diary' THEN '💭'
  WHEN 'Your Inner Voice' THEN '🗣️'
  WHEN 'Growth Mindset' THEN '🌱'
  WHEN 'Childhood' THEN '🧒'
  WHEN 'Teen Years' THEN '🎒'
  -- Energize
  WHEN 'Affection Practice' THEN '💕'
  WHEN 'Fun Times' THEN '🎉'
  -- Calm
  WHEN 'Honest Reviews' THEN '📝'
  WHEN 'First Impressions' THEN '👀'
  WHEN 'Work Cooldown' THEN '🧊'
  WHEN 'Feel Better' THEN '🩹'
  WHEN 'Moment of Vulnerability' THEN '🥺'
  WHEN 'Regroup Time' THEN '🧘'
  WHEN 'Rant Zone' THEN '🌋'
  WHEN 'Thoughts Dump' THEN '🧠'
  -- Night
  WHEN 'Night Reflection' THEN '🌙'
  WHEN 'Today I Learned' THEN '📚'
  WHEN 'Giving Kindness' THEN '🤲'
  WHEN 'Appreciating Kindness of Others' THEN '🥰'
  WHEN 'Value of Kindness' THEN '💛'
  -- Big Picture
  WHEN 'Weekly Look Forward' THEN '📅'
  WHEN 'Yearly Lookback' THEN '🗓️'
  WHEN 'Romantic Partners' THEN '❤️'
  WHEN 'Friendships' THEN '👯'
  WHEN 'Living to the Fullest' THEN '🌟'
  WHEN 'Hypothetical Scenarios' THEN '🤔'
  WHEN 'Opinions' THEN '💡'
  WHEN 'Past Romances' THEN '💔'
  WHEN 'Perspective' THEN '🔭'
  WHEN 'Family' THEN '👨‍👩‍👧'
  WHEN 'Parenting' THEN '👶'
  WHEN 'Spending Habits' THEN '💰'
  WHEN 'Memory Lane' THEN '📸'
  WHEN 'Deep Thoughts' THEN '🌊'
  WHEN 'Life Values' THEN '⚖️'
  WHEN 'Adulting' THEN '🏠'
  ELSE emoji
END
WHERE emoji IS NULL OR emoji = '';
