-- Refreshed Aperture library (Phase 1, merged final)
INSERT INTO public.aperture_actions (slug, kind, category, title, blurb, why, duration, needs, steps, output, is_published) VALUES
('why-repeat-customers-arent-coming-back', 'playbook', 'Customers', 'Why aren''t your repeat customers coming back?', 'Walk through what you know about returners and find one fix to test this week.', 'Most sales are first-timers with a low repeat rate — usually the cheapest growth lever available.', '8 min', ARRAY['basics','customers','money']::text[], '[{"prompt": "Roughly what % of last month''s sales were repeat customers?", "exampleAnswer": "Maybe 15\u201320%, hard to say."}, {"prompt": "When someone buys for the first time, what (if anything) do you do to bring them back?", "exampleAnswer": "Nothing really \u2014 they pay and leave."}, {"prompt": "What do your best returning customers have in common?", "exampleAnswer": "They live nearby and come on weekends."}, {"prompt": "If you could only do ONE thing this week to bring a first-timer back, what feels easiest?", "exampleAnswer": "A little card with a code maybe."}]'::jsonb, NULL, true),
('first-instagram-month', 'playbook', 'Marketing', 'Plan your first real month on Instagram', 'Three posts a week, no overthinking, built around what you actually sell.', 'When the marketing bucket is mostly empty and posting "feels stuck," the smallest possible plan beats a perfect one.', '12 min', ARRAY['basics','marketing','products']::text[], '[{"prompt": "What are the 3 things you''d most want a stranger to know about your business?"}, {"prompt": "Pick one type of post you can commit to: behind-the-scenes, customer reactions, or product close-ups."}, {"prompt": "Best time of week for you to spend 20 minutes filming?"}]'::jsonb, NULL, true),
('pricing-sanity-check', 'playbook', 'Pricing', 'Are you pricing your products correctly?', 'A quick pressure-test on whether your top sellers are leaving money on the table.', 'Pricing by watching competitors is a common trap when your costs and audience are different from theirs.', '10 min', ARRAY['basics','money','customers']::text[], '[{"prompt": "What''s your single best-selling item, and what do you charge for it?"}, {"prompt": "What does it cost you to make or deliver one (rough number is fine)?"}, {"prompt": "When customers buy it, do they ever flinch at the price, or accept it instantly?"}, {"prompt": "If you raised it by $1, what''s the worst that could happen?"}]'::jsonb, NULL, true),
('fix-a-slow-week', 'playbook', 'Sales', 'Fix a slow week', 'Something to actually do — not generic "post more" advice.', 'When this week is slower than usual, the goal is finding the one lever you can pull in 48 hours, not a long-term strategy.', '6 min', ARRAY['basics','customers','money']::text[], '[{"prompt": "How slow are we talking \u2014 20% down, half, almost zero?"}, {"prompt": "Anything different about this week (weather, holiday, you doing less)?"}, {"prompt": "Who are the 5 people most likely to buy from you in the next 3 days?"}]'::jsonb, NULL, true),
('not-enough-customers', 'playbook', 'Marketing', 'I''m not getting enough customers — what do I do?', 'Find exactly where you''re losing people before throwing more effort at marketing.', '"Not enough customers" is rarely one problem — it''s awareness, trust, or conversion, and each needs a different fix.', '10 min', ARRAY['customers','marketing','sales']::text[], '[{"prompt": "When someone hears about you for the first time, where does that usually happen?"}, {"prompt": "Of the people who find you, about how many actually reach out or walk in?"}, {"prompt": "Of the people who reach out, about how many actually buy?"}, {"prompt": "Based on those numbers, where does it feel like people are dropping off most?"}]'::jsonb, NULL, true),
('plan-a-promotion', 'playbook', 'Marketing', 'I want to run a promotion — help me plan it', 'A complete mini campaign — the offer, the message, who gets it, and when.', 'Most owners jump straight to "10% off everything" without deciding what the promotion is actually supposed to do.', '12 min', ARRAY['products','customers','marketing','money']::text[], '[{"prompt": "What''s the real goal here \u2014 new customers, bringing back old ones, or cash this week?"}, {"prompt": "What can you offer that''s attractive to you to give and to them to get?"}, {"prompt": "Who specifically should see this \u2014 everyone, or one group?"}, {"prompt": "When does it start, when does it end, and where will you announce it?"}]'::jsonb, NULL, true),
('raise-prices-with-confidence', 'playbook', 'Pricing', 'I want to raise my prices but I''m scared', 'The math behind a price increase, plus a ready announcement.', 'Most owners avoid a needed price increase out of fear, not because the numbers say no.', '10 min', ARRAY['money','products','customers','competitors']::text[], '[{"prompt": "What do you charge now, and what''s it cost you to deliver?"}, {"prompt": "What do similar businesses near you charge for the same thing?"}, {"prompt": "If you raised it, which clients do you think would actually leave?"}, {"prompt": "Based on that, what new price feels right to test?"}]'::jsonb, NULL, true),
('prepare-for-a-slow-month', 'playbook', 'Sales', 'I have a slow month coming — what should I do now?', 'A plan built before the slow month hits, not a scramble during it.', 'Owners who see a slow period coming and prepare in advance fare better than those who just wait it out.', '10 min', ARRAY['money','customers','marketing','products']::text[], '[{"prompt": "How slow, and is it seasonal or something else this time?"}, {"prompt": "Who are your past customers most likely to respond to a nudge right now?"}, {"prompt": "Is there a promotion, upsell, or reactivation that fits the timing?"}, {"prompt": "What''s the one thing you''ll actually do this week to get ahead of it?"}]'::jsonb, NULL, true),
('build-repeat-customers', 'playbook', 'Customers', 'I want more repeat customers — where do I start?', 'One simple, doable thing that brings people back — not a full loyalty program.', 'Relying mostly on new customers is expensive and fragile; a small repeat-customer system is usually the fastest profit lever.', '10 min', ARRAY['customers','sales','money']::text[], '[{"prompt": "Who are your best repeat customers right now, and what do they have in common?"}, {"prompt": "What''s stopping a first-time buyer from becoming one of them?"}, {"prompt": "What''s the smallest possible thing you could do after someone''s first purchase?"}, {"prompt": "When would you actually do that \u2014 same day, next week, after 30 days?"}]'::jsonb, NULL, true),
('monthly-content-plan', 'playbook', 'Marketing', 'Help me plan what to post this month', 'A 30-day content plan with actual post ideas, not just a calendar grid.', 'Most owners don''t lack ideas, they lack a rhythm — and a blank content calendar is intimidating.', '12 min', ARRAY['marketing','products','customers']::text[], '[{"prompt": "What are the 3 things you want people to know about your business right now?"}, {"prompt": "What do your customers ask or comment on most?"}, {"prompt": "How often can you realistically post without it becoming a chore?"}, {"prompt": "Let''s turn that into 15-20 specific post ideas."}]'::jsonb, NULL, true),
('fix-lead-leakage', 'playbook', 'Sales', 'I keep losing leads — something is wrong', 'Find the pattern in the deals that got away, instead of guessing.', 'Most "we keep losing leads" problems trace back to one repeated cause — speed, price, trust, or follow-up — once you actually look.', '10 min', ARRAY['sales','customers','products']::text[], '[{"prompt": "Think of the last 3-5 people who didn''t buy after showing interest \u2014 what happened with each?"}, {"prompt": "Did you respond quickly, or did some time pass before you got back to them?"}, {"prompt": "When they went quiet, did you follow up \u2014 and if so, how many times?"}, {"prompt": "Looking at those answers, what''s the one thing that shows up most?"}]'::jsonb, NULL, true),
('build-a-review-system', 'playbook', 'Marketing', 'I want to get more reviews — set it up with me', 'A simple, repeatable way to ask for reviews so you stop forgetting.', 'Most owners know reviews matter but have no system, so it only happens when they happen to remember.', '8 min', ARRAY['marketing','customers','operations']::text[], '[{"prompt": "Where do reviews matter most for your business \u2014 Google, Instagram, somewhere else?"}, {"prompt": "What''s the best moment after a purchase to ask?"}, {"prompt": "What''s the easiest way for you to actually ask \u2014 in person, text, automatic?"}, {"prompt": "Let''s build the message and the habit together."}]'::jsonb, NULL, true),
('follow-up-message', 'prompt', 'Customers', 'Draft a follow-up to a quiet customer', 'A short, warm message to someone who used to buy and stopped.', 'Most owners feel awkward sending these — Aperture writes the version you''d actually send.', '1 min', ARRAY['basics','customers']::text[], '[]'::jsonb, 'Hi Mariam! Realized I haven''t seen you in a few weeks — hope everything''s good. We have a new orange cake starting tomorrow, thought of you. No pressure, just wanted to say hi.', true),
('instagram-caption', 'prompt', 'Marketing', 'Write an Instagram caption', 'A caption for your next post, in your voice — not corporate AI tone.', 'Captions are usually the bottleneck for owners who post once a week.', '1 min', ARRAY['basics','marketing','customers']::text[], '[]'::jsonb, 'Quiet Saturday morning at the bakery. The cardamom buns just came out — they always sell out by 11. If you''re in the neighborhood, you know what to do. 🥐', true),
('weekly-priorities', 'prompt', 'Mindset', 'What should I focus on this week?', 'Three priorities based on everything Aperture knows about your business right now.', 'The "where do I even start" question, answered specifically for you instead of generically.', '1 min', ARRAY['basics','vision']::text[], '[]'::jsonb, '1. Ship one Instagram post about the cardamom buns (your proven seller). 2. Send 5 follow-up messages to quiet repeat customers. 3. Decide if you''re raising the bun price to $5 — your cost math says yes.', true),
('raise-prices-script', 'prompt', 'Pricing', 'Tell customers you''re raising prices', 'A short, confident note that doesn''t apologize.', 'You said you''ve been wanting to raise prices for months but freeze up.', '2 min', ARRAY['basics','customers']::text[], '[]'::jsonb, 'Small heads-up: starting next Monday, our cardamom buns are going up to $5. Costs went up, and I want to keep using the good butter. Thanks for understanding — it means I get to keep doing this.', true),
('promotion-announcement', 'prompt', 'Marketing', 'Write a promotion announcement', 'A short, ready-to-post announcement for a sale or special offer.', 'Announcing a promo well takes more thought than it seems — too salesy and people tune out, too quiet and nobody notices.', '2 min', ARRAY['products','customers','marketing']::text[], '[]'::jsonb, 'This Friday only — bring a friend and you both get $5 off your blowout. We''ve got 4 chairs open after 2pm, first come first served. See you then! 💛', true),
('reply-to-inquiry', 'prompt', 'Sales', 'Reply to a customer inquiry', 'A ready response for the question you get asked most.', 'The same 2-3 questions eat up most of an owner''s DM time — having a strong default reply saves real hours.', '2 min', ARRAY['products','sales','customers']::text[], '[]'::jsonb, 'Hey! Yes we do gel manicures, $45 and takes about 45 min. We''re open till 7 today if you want to swing by, or I can hold you a slot for tomorrow morning — just let me know what works!', true),
('reply-to-bad-review', 'prompt', 'Marketing', 'Reply to a bad review', 'A calm, professional public reply that protects your reputation without sounding defensive.', 'How you respond to a bad review is often seen by more people than the review itself.', '3 min', ARRAY['marketing','customers']::text[], '[]'::jsonb, 'Hi Daniel, sorry to hear the wait was longer than expected that day — we had two staff out sick and got behind. That''s on us, not you. Would love a chance to make it right next time, just ask for Sara when you come in.', true),
('ask-for-review', 'prompt', 'Marketing', 'Ask a customer for a review', 'A natural way to ask for a Google or Instagram review without sounding awkward.', 'Most owners want more reviews but freeze up when it''s time to actually ask.', '1 min', ARRAY['customers','marketing']::text[], '[]'::jsonb, 'So glad you loved the cut! If you have 30 seconds, a quick Google review would mean a lot — it really helps people like you find us. Here''s the link: [link]. Thank you! 🙏', true),
('win-back-message', 'prompt', 'Customers', 'Write a win-back message', 'A message to someone who hasn''t been back in a while.', 'Reconnecting with a lapsed customer is usually cheaper and faster than finding a new one.', '2 min', ARRAY['customers','sales']::text[], '[]'::jsonb, 'Hi Reza, it''s been a couple months since your last visit — hope you''ve been well! We just brought in a new espresso blend I think you''d really like. Would love to see you again sometime soon.', true),
('price-increase-message', 'prompt', 'Pricing', 'Write a price increase announcement', 'A confident message to existing clients about a price change — no over-apologizing.', 'Most owners either avoid raising prices entirely or apologize so much it undercuts the message.', '3 min', ARRAY['products','customers','money']::text[], '[]'::jsonb, 'Starting next month, our standard cut is going from $40 to $45. Costs have gone up on our end and it''s time we adjusted — thank you for understanding, and for being one of our regulars. See you soon!', true),
('instagram-bio-rewrite', 'prompt', 'Marketing', 'Rewrite my Instagram bio', 'A bio that passes the 5-second clarity test for someone who''s never heard of you.', 'Most bios describe a feeling instead of saying clearly what the business does and for whom.', '2 min', ARRAY['basics','products','customers']::text[], '[]'::jsonb, 'Persian home-style bakery in Irvine 🍰
Fresh cardamom buns, custom cakes, daily pastries
Order ahead or walk in — closed Mondays', true),
('welcome-message', 'prompt', 'Customers', 'Write a welcome message for a new customer', 'A warm first message that sets the right tone from day one.', 'First impressions after the first purchase shape whether someone becomes a repeat customer.', '1 min', ARRAY['customers','products','sales']::text[], '[]'::jsonb, 'Welcome to the family, Layla! So happy you booked with us. If you ever have questions before your appointment, just message here — see you Thursday at 2!', true),
('thank-you-message', 'prompt', 'Customers', 'Write a thank you message after a purchase', 'A short, genuine thank you — specific to what they bought, not generic.', 'A specific thank you feels personal; a generic one feels automated.', '1 min', ARRAY['customers','products']::text[], '[]'::jsonb, 'Thank you for picking up the birthday cake today! Hope it was the highlight of the party 🎂 Can''t wait to make the next one whenever you''re ready.', true),
('referral-ask', 'prompt', 'Sales', 'Write a referral ask', 'A natural way to ask happy customers to send friends your way.', 'Most owners worry referral asks sound pushy, so they never ask at all — even their happiest customers.', '2 min', ARRAY['customers','marketing','sales']::text[], '[]'::jsonb, 'So glad you''re loving the results! If you know anyone else looking for a stylist, send them my way — I''ll take great care of them too. And thank you for trusting me with your hair 💛', true)
ON CONFLICT (slug) DO UPDATE SET
  kind = EXCLUDED.kind,
  category = EXCLUDED.category,
  title = EXCLUDED.title,
  blurb = EXCLUDED.blurb,
  why = EXCLUDED.why,
  duration = EXCLUDED.duration,
  needs = EXCLUDED.needs,
  steps = EXCLUDED.steps,
  output = EXCLUDED.output,
  is_published = true,
  updated_at = now();

-- Unpublish anything not in the merged set so Library shows the canonical 28 only
UPDATE public.aperture_actions SET is_published = false, updated_at = now() WHERE slug NOT IN ('why-repeat-customers-arent-coming-back','first-instagram-month','pricing-sanity-check','fix-a-slow-week','not-enough-customers','plan-a-promotion','raise-prices-with-confidence','prepare-for-a-slow-month','build-repeat-customers','monthly-content-plan','fix-lead-leakage','build-a-review-system','follow-up-message','instagram-caption','weekly-priorities','raise-prices-script','promotion-announcement','reply-to-inquiry','reply-to-bad-review','ask-for-review','win-back-message','price-increase-message','instagram-bio-rewrite','welcome-message','thank-you-message','referral-ask');
