
INSERT INTO admin_task_bank (title, emoji, category, color, tag, duration_minutes, repeat_pattern, sort_order, description) VALUES
('Wind-down routine at 10pm', '😴', 'sleep', 'lavender', 'wr-felt-good:Sleep', 10, 'daily', 900, 'Easy · 10 min'),
('Eat a home-cooked meal', '🥗', 'nutrition', 'mint', 'wr-felt-good:Nutrition', 30, 'daily', 901, 'Medium · 30 min'),
('Read for 15 minutes', '📚', 'Presence', 'yellow', 'wr-felt-good:Learning', 15, 'daily', 902, 'Easy · 15 min'),
('30-min workout', '🏃', 'Exercise', 'peach', 'wr-felt-good:Physical activities', 30, 'daily', 903, 'Medium · 30 min'),
('5-min morning meditation', '🧘', 'calm', 'lavender', 'wr-felt-good:Mindfulness', 5, 'daily', 904, 'Easy · 5 min'),
('Take a relaxing bath', '🛀', 'wellness', 'sky', 'wr-felt-good:Relaxation', 20, 'daily', 905, 'Easy · 20 min'),
('20-min nature walk', '🌿', 'movement', 'mint', 'wr-felt-good:Nature', 20, 'daily', 906, 'Easy · 20 min'),
('Review notes for 20 min', '🎓', 'productivity', 'sky', 'wr-felt-good:School', 20, 'daily', 907, 'Medium · 20 min'),
('Plan top 3 priorities', '💼', 'productivity', 'sky', 'wr-felt-good:Work', 5, 'daily', 908, 'Easy · 5 min'),
('Quality family time', '👨‍👩‍👧', 'LovedOnes', 'pink', 'wr-felt-good:Family', 30, 'daily', 909, 'Easy · 30 min'),
('Reach out to a friend', '🤝', 'connection', 'peach', 'wr-felt-good:Friends', 5, 'daily', 910, 'Easy · 5 min'),
('Plan a date night', '💑', 'connection', 'pink', 'wr-felt-good:Partner', 10, 'daily', 911, 'Easy · 10 min'),
('Extra playtime with pet', '🐾', 'Pets-Reset', 'yellow', 'wr-felt-good:Pet', 15, 'daily', 912, 'Easy · 15 min'),
('Join a local event', '🏘️', 'connection', 'mint', 'wr-felt-good:Community', 60, 'daily', 913, 'Medium · 1 hr'),
('Time-block your day', '⚡', 'productivity', 'peach', 'wr-felt-good:Productivity', 10, 'daily', 914, 'Easy · 10 min'),
('Celebrate a small win', '🏆', 'gratitude', 'yellow', 'wr-felt-good:Achievement', 5, 'daily', 915, 'Easy · 5 min'),
('Spend 30 min on a hobby', '🎨', 'Presence', 'lavender', 'wr-felt-good:Hobbies', 30, 'daily', 916, 'Easy · 30 min'),
('Try something creative', '✏️', 'Presence', 'pink', 'wr-felt-good:Creativity', 20, 'daily', 917, 'Easy · 20 min'),
('No screens after 9pm', '🌙', 'sleep', 'lavender', 'wr-focus:Sleep better', 1, 'daily', 920, 'Medium · Daily'),
('Meal prep Sunday', '🥑', 'nutrition', 'mint', 'wr-focus:Eat healthier', 60, 'weekly', 921, 'Medium · 1 hr'),
('Walk 10,000 steps', '💪', 'movement', 'peach', 'wr-focus:Be more active', 1, 'daily', 922, 'Medium · Daily'),
('Practice mindful breathing', '🧠', 'calm', 'lavender', 'wr-focus:Be present', 5, 'daily', 923, 'Easy · 5 min'),
('Breathing exercise 2x daily', '🕊️', 'calm', 'sky', 'wr-focus:Stay calm', 5, 'daily', 924, 'Easy · 5 min'),
('Write 3 things I''m proud of', '💚', 'self-kindness', 'mint', 'wr-focus:Be kind to self', 5, 'daily', 925, 'Easy · 5 min'),
('Plan tomorrow before bed', '📋', 'productivity', 'yellow', 'wr-focus:Be organized', 5, 'daily', 926, 'Easy · 5 min'),
('Complete top priority first', '🎯', 'productivity', 'peach', 'wr-focus:Get things done', 1, 'daily', 927, 'Medium · Daily'),
('Do something fun for 30 min', '🌈', 'Presence', 'pink', 'wr-focus:Find joy', 30, 'daily', 928, 'Easy · 30 min'),
('Send a kind message', '💕', 'connection', 'pink', 'wr-focus:Feel more connected', 5, 'daily', 929, 'Easy · 5 min'),
('Morning stretch routine', '🌅', 'movement', 'yellow', 'wr-default', 10, 'daily', 930, 'Easy · 10 min'),
('Drink 8 glasses of water', '💧', 'wellness', 'sky', 'wr-default', 1, 'daily', 931, 'Easy · Daily'),
('Read for 15 minutes daily', '📖', 'Presence', 'lavender', 'wr-default', 15, 'daily', 932, 'Easy · 15 min');
