-- Insert all task templates with their categories
-- Using consistent emojis and colors per category

INSERT INTO public.task_templates (title, category, emoji, color, repeat_pattern, is_active, display_order) VALUES
-- Survival & Morning Basics (blue theme)
('Literally survive the day', 'Survival & Morning Basics', '💪', 'blue', 'daily', true, 1),
('Just be', 'Survival & Morning Basics', '🧘', 'blue', 'daily', true, 2),
('Drink water', 'Survival & Morning Basics', '💧', 'blue', 'daily', true, 3),
('Drink hot water', 'Survival & Morning Basics', '☕', 'blue', 'daily', true, 4),
('Get out of bed', 'Survival & Morning Basics', '🛏️', 'blue', 'daily', true, 5),
('Change clothes', 'Survival & Morning Basics', '👕', 'blue', 'daily', true, 6),
('Take 3 deep breaths', 'Survival & Morning Basics', '🌬️', 'blue', 'daily', true, 7),
('Brush teeth', 'Survival & Morning Basics', '🪥', 'blue', 'daily', true, 8),
('Wash face', 'Survival & Morning Basics', '🧴', 'blue', 'daily', true, 9),
('Look in the mirror and say "I can do it"', 'Survival & Morning Basics', '🪞', 'blue', 'daily', true, 10),
('Stand up for 10 seconds', 'Survival & Morning Basics', '🧍', 'blue', 'daily', true, 11),
('Step outside once', 'Survival & Morning Basics', '🚪', 'blue', 'daily', true, 12),
('Take a shower', 'Survival & Morning Basics', '🚿', 'blue', 'daily', true, 13),
('Floss my teeth', 'Survival & Morning Basics', '🦷', 'blue', 'daily', true, 14),
('Wash my hands when I get home', 'Survival & Morning Basics', '🧼', 'blue', 'daily', true, 15),
('Brush my hair', 'Survival & Morning Basics', '💇', 'blue', 'daily', true, 16),
('Wear clean clothes', 'Survival & Morning Basics', '👔', 'blue', 'daily', true, 17),
('Wear clean socks', 'Survival & Morning Basics', '🧦', 'blue', 'daily', true, 18),

-- Mental Health & Mindfulness (purple theme)
('Do a mindful breathing exercise', 'Mental Health & Mindfulness', '🧘‍♀️', 'purple', 'daily', true, 19),
('Avoid doomscrolling in bed', 'Mental Health & Mindfulness', '📵', 'purple', 'daily', true, 20),
('Name how I''m feeling right now', 'Mental Health & Mindfulness', '💭', 'purple', 'daily', true, 21),
('Write down all my thoughts and worries', 'Mental Health & Mindfulness', '📝', 'purple', 'daily', true, 22),
('Visualize a peaceful place', 'Mental Health & Mindfulness', '🏝️', 'purple', 'daily', true, 23),
('Light a candle', 'Mental Health & Mindfulness', '🕯️', 'purple', 'daily', true, 24),
('Do a quick body scan for tension or relaxation', 'Mental Health & Mindfulness', '🫀', 'purple', 'daily', true, 25),
('Wrap myself in a cozy blanket', 'Mental Health & Mindfulness', '🛋️', 'purple', 'daily', true, 26),
('Give myself permission to rest', 'Mental Health & Mindfulness', '😌', 'purple', 'daily', true, 27),
('Give myself a hug', 'Mental Health & Mindfulness', '🤗', 'purple', 'daily', true, 28),
('Say one kind thing to myself as if I were a friend', 'Mental Health & Mindfulness', '💕', 'purple', 'daily', true, 29),
('Thank myself for making it through the day', 'Mental Health & Mindfulness', '🙏', 'purple', 'daily', true, 30),
('Read a simple affirmation for myself', 'Mental Health & Mindfulness', '✨', 'purple', 'daily', true, 31),
('Start your day with an affirmation', 'Mental Health & Mindfulness', '🌅', 'purple', 'daily', true, 32),
('Smile at myself in the mirror', 'Mental Health & Mindfulness', '😊', 'purple', 'daily', true, 33),
('Accept that I''m a work in progress', 'Mental Health & Mindfulness', '🌱', 'purple', 'daily', true, 34),
('Name one quality I''m developing', 'Mental Health & Mindfulness', '💎', 'purple', 'daily', true, 35),
('Embrace an imperfection as part of what makes me unique', 'Mental Health & Mindfulness', '🦋', 'purple', 'daily', true, 36),
('Allow myself to feel my emotions without judgment', 'Mental Health & Mindfulness', '💜', 'purple', 'daily', true, 37),
('Say "I accept myself as I am right now"', 'Mental Health & Mindfulness', '🤍', 'purple', 'daily', true, 38),
('Replace "I should" with "I choose to"', 'Mental Health & Mindfulness', '🔄', 'purple', 'daily', true, 39),
('Tell myself "I just need to do my best" when overwhelmed', 'Mental Health & Mindfulness', '🌟', 'purple', 'daily', true, 40),

-- Gratitude & Reflection (yellow/gold theme)
('Say one thing I''m grateful for before bed', 'Gratitude & Reflection', '🙏', 'yellow', 'daily', true, 41),
('Name one person who cares for me', 'Gratitude & Reflection', '❤️', 'yellow', 'daily', true, 42),
('Think of someone who helped me today', 'Gratitude & Reflection', '🤝', 'yellow', 'daily', true, 43),
('Name one thing I''m grateful to my body for', 'Gratitude & Reflection', '💪', 'yellow', 'daily', true, 44),
('Name one thing I like about myself', 'Gratitude & Reflection', '🌟', 'yellow', 'daily', true, 45),
('Name one small success from today', 'Gratitude & Reflection', '🏆', 'yellow', 'daily', true, 46),
('Notice a small joy in my day', 'Gratitude & Reflection', '😊', 'yellow', 'daily', true, 47),
('Write one thing in a gratitude reflection', 'Gratitude & Reflection', '📓', 'yellow', 'daily', true, 48),
('Name one thing that made me happy today', 'Gratitude & Reflection', '😄', 'yellow', 'daily', true, 49),
('Take a moment to breathe the fresh air', 'Gratitude & Reflection', '🌿', 'yellow', 'daily', true, 50),
('Look at the sky and appreciate its beauty', 'Gratitude & Reflection', '🌤️', 'yellow', 'daily', true, 51),
('Notice one thing around me that brings me peace', 'Gratitude & Reflection', '☮️', 'yellow', 'daily', true, 52),
('Treat one everyday object like a gift', 'Gratitude & Reflection', '🎁', 'yellow', 'daily', true, 53),
('Think about a favorite memory', 'Gratitude & Reflection', '📸', 'yellow', 'daily', true, 54),
('Think about how chores make my life better', 'Gratitude & Reflection', '🏠', 'yellow', 'daily', true, 55),
('Appreciate how cozy my bed is before getting up', 'Gratitude & Reflection', '🛏️', 'yellow', 'daily', true, 56),

-- Nutrition & Healthy Eating (green theme)
('Enjoy lunch without screen time', 'Nutrition & Healthy Eating', '🍽️', 'green', 'daily', true, 57),
('Eat a healthy meal', 'Nutrition & Healthy Eating', '🥗', 'green', 'daily', true, 58),
('Avoid sugary drinks', 'Nutrition & Healthy Eating', '🚫', 'green', 'daily', true, 59),
('Eat a healthy snack like whole fruit or nuts', 'Nutrition & Healthy Eating', '🍎', 'green', 'daily', true, 60),
('Fill my water bottle', 'Nutrition & Healthy Eating', '💧', 'green', 'daily', true, 61),
('Keep a water bottle around throughout the day', 'Nutrition & Healthy Eating', '🫗', 'green', 'daily', true, 62),
('Use a smaller plate for portion control', 'Nutrition & Healthy Eating', '🍽️', 'green', 'daily', true, 63),
('Buy a healthy snack from the grocery store', 'Nutrition & Healthy Eating', '🛒', 'green', 'weekly', true, 64),
('Add a vegetable to my meal', 'Nutrition & Healthy Eating', '🥦', 'green', 'daily', true, 65),
('Put my fork down between each bite of food', 'Nutrition & Healthy Eating', '🍴', 'green', 'daily', true, 66),
('Eat my meal without my phone or TV', 'Nutrition & Healthy Eating', '📵', 'green', 'daily', true, 67),
('Drink a cup of tea', 'Nutrition & Healthy Eating', '🍵', 'green', 'daily', true, 68),
('Drink a glass of water with every meal', 'Nutrition & Healthy Eating', '🥛', 'green', 'daily', true, 69),
('Savor each bite of my meal', 'Nutrition & Healthy Eating', '😋', 'green', 'daily', true, 70),
('Pack a healthy snack for the day', 'Nutrition & Healthy Eating', '🎒', 'green', 'daily', true, 71),
('Plan out my meals for the next day', 'Nutrition & Healthy Eating', '📋', 'green', 'daily', true, 72),
('Try one new recipe', 'Nutrition & Healthy Eating', '👨‍🍳', 'green', 'weekly', true, 73),
('Cook a meal for myself', 'Nutrition & Healthy Eating', '🍳', 'green', 'daily', true, 74),
('Incorporate whole grains in my meal', 'Nutrition & Healthy Eating', '🌾', 'green', 'daily', true, 75),
('Pause and appreciate the food I''m about to eat', 'Nutrition & Healthy Eating', '🙏', 'green', 'daily', true, 76),

-- Physical Activity & Body Care (orange theme)
('Take a walk in nature', 'Physical Activity & Body Care', '🚶‍♀️', 'orange', 'daily', true, 77),
('Take a short walk without distraction', 'Physical Activity & Body Care', '🚶', 'orange', 'daily', true, 78),
('Take a stretch break', 'Physical Activity & Body Care', '🧘', 'orange', 'daily', true, 79),
('Go for a 5-minute walk', 'Physical Activity & Body Care', '👟', 'orange', 'daily', true, 80),
('Perform a 3-minute exercise I enjoy', 'Physical Activity & Body Care', '🏃', 'orange', 'daily', true, 81),
('Dance to a song I like', 'Physical Activity & Body Care', '💃', 'orange', 'daily', true, 82),
('Take the stairs', 'Physical Activity & Body Care', '🪜', 'orange', 'daily', true, 83),
('Walk around my neighborhood', 'Physical Activity & Body Care', '🏘️', 'orange', 'daily', true, 84),
('Start my day with morning stretches', 'Physical Activity & Body Care', '🌅', 'orange', 'daily', true, 85),
('End my day with wind down stretches', 'Physical Activity & Body Care', '🌙', 'orange', 'daily', true, 86),
('Do 10 shoulder rolls', 'Physical Activity & Body Care', '🔄', 'orange', 'daily', true, 87),
('Hold a plank for 10 seconds', 'Physical Activity & Body Care', '💪', 'orange', 'daily', true, 88),
('Do 5 jumping jacks', 'Physical Activity & Body Care', '⭐', 'orange', 'daily', true, 89),
('Do 5 squats', 'Physical Activity & Body Care', '🦵', 'orange', 'daily', true, 90),
('Do 5 wall push ups', 'Physical Activity & Body Care', '🧱', 'orange', 'daily', true, 91),
('Do 5 sit-ups', 'Physical Activity & Body Care', '🔥', 'orange', 'daily', true, 92),
('Do 10 lunges', 'Physical Activity & Body Care', '🏋️', 'orange', 'daily', true, 93),
('Pace around during a call', 'Physical Activity & Body Care', '📞', 'orange', 'daily', true, 94),
('Stand up once while watching TV', 'Physical Activity & Body Care', '📺', 'orange', 'daily', true, 95),
('Go for a short walk after my meal', 'Physical Activity & Body Care', '🚶‍♂️', 'orange', 'daily', true, 96),
('Trim my nails', 'Physical Activity & Body Care', '💅', 'orange', 'weekly', true, 97),
('Moisturize my skin', 'Physical Activity & Body Care', '🧴', 'orange', 'daily', true, 98),
('Apply sunscreen before going outside', 'Physical Activity & Body Care', '☀️', 'orange', 'daily', true, 99),

-- Social Connections & Community (pink theme)
('Compliment someone', 'Social Connections & Community', '💬', 'pink', 'daily', true, 100),
('Say thank you to someone', 'Social Connections & Community', '🙏', 'pink', 'daily', true, 101),
('Express gratitude to a loved one', 'Social Connections & Community', '❤️', 'pink', 'daily', true, 102),
('Share a smile with someone around me', 'Social Connections & Community', '😊', 'pink', 'daily', true, 103),
('Give someone a warm hug', 'Social Connections & Community', '🤗', 'pink', 'daily', true, 104),
('Ask someone how their day is going', 'Social Connections & Community', '💭', 'pink', 'daily', true, 105),
('Tell a loved one I love them', 'Social Connections & Community', '💕', 'pink', 'daily', true, 106),
('Hug a loved one before bed', 'Social Connections & Community', '🫂', 'pink', 'daily', true, 107),
('Take a photo with a loved one', 'Social Connections & Community', '📸', 'pink', 'weekly', true, 108),
('Call a loved one', 'Social Connections & Community', '📱', 'pink', 'weekly', true, 109),
('Share one thing about my day with a loved one', 'Social Connections & Community', '🗣️', 'pink', 'daily', true, 110),
('Put my phone away when spending time with a loved one', 'Social Connections & Community', '📵', 'pink', 'daily', true, 111),
('Check in on someone I care about', 'Social Connections & Community', '💝', 'pink', 'weekly', true, 112),
('Cook a family meal together', 'Social Connections & Community', '👨‍👩‍👧', 'pink', 'weekly', true, 113),
('Spend quality time with family', 'Social Connections & Community', '👪', 'pink', 'daily', true, 114),
('Message a friend', 'Social Connections & Community', '💌', 'pink', 'daily', true, 115),
('Send a funny post to a friend', 'Social Connections & Community', '😂', 'pink', 'daily', true, 116),
('Invite a friend to run errands together', 'Social Connections & Community', '🛍️', 'pink', 'weekly', true, 117),
('Say hello to a neighbor', 'Social Connections & Community', '👋', 'pink', 'daily', true, 118),
('Help out a neighbor', 'Social Connections & Community', '🤝', 'pink', 'weekly', true, 119),
('Volunteer with a local organization', 'Social Connections & Community', '🎗️', 'pink', 'weekly', true, 120),
('Attend a club or meetup event', 'Social Connections & Community', '🎉', 'pink', 'weekly', true, 121),
('Tend to a community garden', 'Social Connections & Community', '🌻', 'pink', 'weekly', true, 122),

-- Productivity & Home Care (slate/gray theme)
('Turn off notifications for 1 hour', 'Productivity & Home Care', '🔕', 'slate', 'daily', true, 123),
('Close unused browser tabs', 'Productivity & Home Care', '🗂️', 'slate', 'daily', true, 124),
('Stop working by 6pm', 'Productivity & Home Care', '⏰', 'slate', 'daily', true, 125),
('Write down my goals for tomorrow', 'Productivity & Home Care', '📝', 'slate', 'daily', true, 126),
('Write down my goals in the morning', 'Productivity & Home Care', '🌅', 'slate', 'daily', true, 127),
('Check off one item from my to-do list', 'Productivity & Home Care', '✅', 'slate', 'daily', true, 128),
('Finish work on time', 'Productivity & Home Care', '🏁', 'slate', 'daily', true, 129),
('Set a deadline for a task', 'Productivity & Home Care', '📅', 'slate', 'daily', true, 130),
('Break a task into smaller steps', 'Productivity & Home Care', '📊', 'slate', 'daily', true, 131),
('Try a focus timer for deep work', 'Productivity & Home Care', '⏱️', 'slate', 'daily', true, 132),
('Start with the most important task', 'Productivity & Home Care', '🎯', 'slate', 'daily', true, 133),
('Name one thing I accomplished at the end of the day', 'Productivity & Home Care', '🏆', 'slate', 'daily', true, 134),
('Listen to a focus playlist', 'Productivity & Home Care', '🎧', 'slate', 'daily', true, 135),
('Write down the first step of my task', 'Productivity & Home Care', '✏️', 'slate', 'daily', true, 136),
('Complete a task before lunch', 'Productivity & Home Care', '☀️', 'slate', 'daily', true, 137),
('Set a specific time to check my messages', 'Productivity & Home Care', '📬', 'slate', 'daily', true, 138),
('Put away one item that is not in its place', 'Productivity & Home Care', '🗄️', 'slate', 'daily', true, 139),
('Declutter my desk', 'Productivity & Home Care', '🖥️', 'slate', 'daily', true, 140),
('Spend 5 minutes tidying my home', 'Productivity & Home Care', '🏠', 'slate', 'daily', true, 141),
('Take out the trash', 'Productivity & Home Care', '🗑️', 'slate', 'daily', true, 142),
('Vacuum my room', 'Productivity & Home Care', '🧹', 'slate', 'weekly', true, 143),
('Wipe down my phone', 'Productivity & Home Care', '📱', 'slate', 'daily', true, 144),
('Disinfect my keyboard', 'Productivity & Home Care', '⌨️', 'slate', 'weekly', true, 145),
('Carry hand sanitizer when I go out', 'Productivity & Home Care', '🧴', 'slate', 'daily', true, 146),
('Wash bathroom towels', 'Productivity & Home Care', '🛁', 'slate', 'weekly', true, 147),
('Clean bed sheets', 'Productivity & Home Care', '🛏️', 'slate', 'weekly', true, 148),
('Do laundry', 'Productivity & Home Care', '🧺', 'slate', 'weekly', true, 149),
('Wipe down bathroom counter', 'Productivity & Home Care', '🪥', 'slate', 'weekly', true, 150),
('Clean water bottle', 'Productivity & Home Care', '🫗', 'slate', 'daily', true, 151),

-- Nighttime & Sleep (indigo theme)
('Wind down with a sleep breathing exercise before bed', 'Nighttime & Sleep', '🌙', 'indigo', 'daily', true, 152),
('Read something relaxing before bed', 'Nighttime & Sleep', '📖', 'indigo', 'daily', true, 153),
('Make myself a cup of chamomile tea after dinner', 'Nighttime & Sleep', '🍵', 'indigo', 'daily', true, 154),
('Listen to a soundscape', 'Nighttime & Sleep', '🎶', 'indigo', 'daily', true, 155),
('Listen to soothing music before bed', 'Nighttime & Sleep', '🎵', 'indigo', 'daily', true, 156),
('Silence notifications before bed', 'Nighttime & Sleep', '🔇', 'indigo', 'daily', true, 157),
('Dim the lights 30 minutes before bed', 'Nighttime & Sleep', '💡', 'indigo', 'daily', true, 158),
('Take a warm shower or bath before bed', 'Nighttime & Sleep', '🛀', 'indigo', 'daily', true, 159),
('Limit social media before bed', 'Nighttime & Sleep', '📵', 'indigo', 'daily', true, 160),
('Close all my curtains for darkness', 'Nighttime & Sleep', '🌑', 'indigo', 'daily', true, 161),
('Make my bed', 'Nighttime & Sleep', '🛏️', 'indigo', 'daily', true, 162),
('Avoid naps longer than 30 minutes', 'Nighttime & Sleep', '⏰', 'indigo', 'daily', true, 163),
('Open my curtains first thing in the morning', 'Nighttime & Sleep', '☀️', 'indigo', 'daily', true, 164),
('Wake up at a consistent time', 'Nighttime & Sleep', '⏰', 'indigo', 'daily', true, 165),
('Go to bed at the same time every night', 'Nighttime & Sleep', '🌙', 'indigo', 'daily', true, 166),
('Avoid caffeine after lunch', 'Nighttime & Sleep', '☕', 'indigo', 'daily', true, 167),
('Avoid heavy meals before bed', 'Nighttime & Sleep', '🍽️', 'indigo', 'daily', true, 168),
('Eat my last meal 3 hours before bed', 'Nighttime & Sleep', '🕐', 'indigo', 'daily', true, 169),
('Skip that drink tonight', 'Nighttime & Sleep', '🍷', 'indigo', 'daily', true, 170);