-- First, delete existing categories (except Pro) and task templates to start fresh
DELETE FROM task_templates;
DELETE FROM routine_categories WHERE slug != 'pro';

-- Insert new categories
INSERT INTO routine_categories (name, slug, icon, color, display_order, is_active) VALUES
('Easy Win', 'easy-win', 'Zap', '#10B981', 1, true),
('Calm', 'calm', 'Wind', '#8B5CF6', 2, true),
('Connection', 'connection', 'Heart', '#EC4899', 3, true),
('Nutrition', 'nutrition', 'Apple', '#22C55E', 4, true),
('Productivity', 'productivity', 'Target', '#3B82F6', 5, true),
('Movement', 'movement', 'Dumbbell', '#F97316', 6, true),
('Self-kindness', 'self-kindness', 'Sparkles', '#F472B6', 7, true),
('Sleep', 'sleep', 'Moon', '#6366F1', 8, true),
('Gratitude', 'gratitude', 'Sun', '#FBBF24', 9, true),
('Hygiene', 'hygiene', 'Droplets', '#06B6D4', 10, true);

-- Insert Easy Win tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Literally survive the day', '💪', 'green', 'easy-win', 1, true),
('Just be', '🧘', 'green', 'easy-win', 2, true),
('Drink water', '💧', 'green', 'easy-win', 3, true),
('Drink hot water', '☕', 'green', 'easy-win', 4, true),
('Get out of bed', '🛏️', 'green', 'easy-win', 5, true),
('Change clothes', '👕', 'green', 'easy-win', 6, true),
('Take 3 deep breaths', '🌬️', 'green', 'easy-win', 7, true),
('Brush teeth', '🪥', 'green', 'easy-win', 8, true),
('Wash face', '🧼', 'green', 'easy-win', 9, true),
('Look in the mirror and say "I can do it"', '🪞', 'green', 'easy-win', 10, true),
('Stand up for 10 seconds', '🧍', 'green', 'easy-win', 11, true),
('Name one person who cares for me', '❤️', 'green', 'easy-win', 12, true),
('Step outside once', '🚶', 'green', 'easy-win', 13, true),
('Take a shower', '🚿', 'green', 'easy-win', 14, true);

-- Insert Calm tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Take 3 deep breaths', '🌬️', 'purple', 'calm', 1, true),
('Do a mindful breathing exercise', '🧘', 'purple', 'calm', 2, true),
('Avoid doomscrolling in bed', '📵', 'purple', 'calm', 3, true),
('Enjoy lunch without screen time', '🍽️', 'purple', 'calm', 4, true),
('Name how I''m feeling right now', '💭', 'purple', 'calm', 5, true),
('Say one thing I''m grateful for before bed', '🙏', 'purple', 'calm', 6, true),
('Write down all my thoughts and worries', '📝', 'purple', 'calm', 7, true),
('Take a water break', '💧', 'purple', 'calm', 8, true),
('Wind down with a sleep breathing exercise before bed', '😴', 'purple', 'calm', 9, true),
('Read something relaxing before bed', '📖', 'purple', 'calm', 10, true),
('Make myself a cup of chamomile tea after dinner', '🍵', 'purple', 'calm', 11, true),
('Turn off notifications for 1 hour', '🔕', 'purple', 'calm', 12, true),
('Close unused browser tabs', '🌐', 'purple', 'calm', 13, true),
('Listen to a soundscape', '🎧', 'purple', 'calm', 14, true),
('Stop working by 6pm', '⏰', 'purple', 'calm', 15, true),
('Avoid mindlessly scrolling social media', '📱', 'purple', 'calm', 16, true),
('Visualize a peaceful place', '🏝️', 'purple', 'calm', 17, true),
('Light a candle', '🕯️', 'purple', 'calm', 18, true),
('Do a quick body scan for tension or relaxation', '🧠', 'purple', 'calm', 19, true),
('Wrap myself in a cozy blanket', '🛋️', 'purple', 'calm', 20, true),
('Take a walk in nature', '🌳', 'purple', 'calm', 21, true),
('Take a short walk without distraction', '🚶', 'purple', 'calm', 22, true),
('Put my fork down between each bite of food', '🍴', 'purple', 'calm', 23, true),
('Eat my meal without my phone or TV', '🍽️', 'purple', 'calm', 24, true);

-- Insert Connection tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Compliment someone', '💬', 'pink', 'connection', 1, true),
('Say thank you to someone', '🙏', 'pink', 'connection', 2, true),
('Think of someone who helped me today', '💭', 'pink', 'connection', 3, true),
('Express gratitude to a loved one', '❤️', 'pink', 'connection', 4, true),
('Name one person who cares for me', '💕', 'pink', 'connection', 5, true),
('Share a smile with someone around me', '😊', 'pink', 'connection', 6, true),
('Give someone a warm hug', '🤗', 'pink', 'connection', 7, true),
('Ask someone how their day is going', '👋', 'pink', 'connection', 8, true),
('Tell a loved one I love them', '💝', 'pink', 'connection', 9, true),
('Hug a loved one before bed', '🫂', 'pink', 'connection', 10, true),
('Take a photo with a loved one', '📸', 'pink', 'connection', 11, true),
('Call a loved one', '📞', 'pink', 'connection', 12, true),
('Share one thing about my day with a loved one', '💬', 'pink', 'connection', 13, true),
('Put my phone away when spending time with a loved one', '📵', 'pink', 'connection', 14, true),
('Check in on someone I care about', '💌', 'pink', 'connection', 15, true),
('Cook a family meal together', '👨‍👩‍👧', 'pink', 'connection', 16, true),
('Spend quality time with family', '🏠', 'pink', 'connection', 17, true),
('Message a friend', '💬', 'pink', 'connection', 18, true),
('Hang out with a friend', '👯', 'pink', 'connection', 19, true),
('Send a funny post to a friend', '😂', 'pink', 'connection', 20, true),
('Invite a friend to run errands together', '🛒', 'pink', 'connection', 21, true),
('Say hello to a neighbor', '👋', 'pink', 'connection', 22, true),
('Help out a neighbor', '🤝', 'pink', 'connection', 23, true),
('Volunteer with a local organization', '🙌', 'pink', 'connection', 24, true),
('Attend a club or meetup event', '🎉', 'pink', 'connection', 25, true),
('Tend to a community garden', '🌱', 'pink', 'connection', 26, true);

-- Insert Nutrition tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Drink water', '💧', 'green', 'nutrition', 1, true),
('Eat a healthy meal', '🥗', 'green', 'nutrition', 2, true),
('Avoid sugary drinks', '🚫', 'green', 'nutrition', 3, true),
('Eat a healthy snack like whole fruit or nuts', '🍎', 'green', 'nutrition', 4, true),
('Fill my water bottle', '🫗', 'green', 'nutrition', 5, true),
('Keep a water bottle around throughout the day', '💧', 'green', 'nutrition', 6, true),
('Use a smaller plate for portion control', '🍽️', 'green', 'nutrition', 7, true),
('Buy a healthy snack from the grocery store', '🛒', 'green', 'nutrition', 8, true),
('Add a vegetable to my meal', '🥦', 'green', 'nutrition', 9, true),
('Put my fork down between each bite of food', '🍴', 'green', 'nutrition', 10, true),
('Eat my meal without my phone or TV', '📵', 'green', 'nutrition', 11, true),
('Skip that drink tonight', '🚫', 'green', 'nutrition', 12, true),
('Drink a cup of tea', '🍵', 'green', 'nutrition', 13, true),
('Drink a glass of water with every meal', '💧', 'green', 'nutrition', 14, true),
('Savor each bite of my meal', '😋', 'green', 'nutrition', 15, true),
('Pack a healthy snack for the day', '🎒', 'green', 'nutrition', 16, true),
('Plan out my meals for the next day', '📋', 'green', 'nutrition', 17, true),
('Try one new recipe', '👨‍🍳', 'green', 'nutrition', 18, true),
('Cook a meal for myself', '🍳', 'green', 'nutrition', 19, true),
('Incorporate whole grains in my meal', '🌾', 'green', 'nutrition', 20, true);

-- Insert Productivity tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Write down my goals for tomorrow', '📝', 'blue', 'productivity', 1, true),
('Turn off notifications for 1 hour', '🔕', 'blue', 'productivity', 2, true),
('Check off one item from my to-do list', '✅', 'blue', 'productivity', 3, true),
('Finish work on time', '⏰', 'blue', 'productivity', 4, true),
('Set a deadline for a task', '📅', 'blue', 'productivity', 5, true),
('Write down my goals in the morning', '🌅', 'blue', 'productivity', 6, true),
('Break a task into smaller steps', '📊', 'blue', 'productivity', 7, true),
('Try a focus timer for deep work', '⏱️', 'blue', 'productivity', 8, true),
('Start with the most important task', '🎯', 'blue', 'productivity', 9, true),
('Name one thing I accomplished at the end of the day', '🏆', 'blue', 'productivity', 10, true),
('Listen to a focus playlist', '🎵', 'blue', 'productivity', 11, true),
('Write down the first step of my task', '1️⃣', 'blue', 'productivity', 12, true),
('Complete a task before lunch', '🍽️', 'blue', 'productivity', 13, true),
('Set a specific time to check my messages', '📬', 'blue', 'productivity', 14, true),
('Close unused browser tabs', '🌐', 'blue', 'productivity', 15, true),
('Put away one item that is not in its place', '🧹', 'blue', 'productivity', 16, true),
('Declutter my desk', '🗃️', 'blue', 'productivity', 17, true),
('Spend 5 minutes tidying my home', '🏠', 'blue', 'productivity', 18, true),
('Take out the trash', '🗑️', 'blue', 'productivity', 19, true),
('Vacuum my room', '🧹', 'blue', 'productivity', 20, true);

-- Insert Movement tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Take a stretch break', '🤸', 'orange', 'movement', 1, true),
('Step outside once', '🚪', 'orange', 'movement', 2, true),
('Go for a 5-minute walk', '🚶', 'orange', 'movement', 3, true),
('Perform a 3-minute exercise I enjoy', '💪', 'orange', 'movement', 4, true),
('Dance to a song I like', '💃', 'orange', 'movement', 5, true),
('Take the stairs', '🪜', 'orange', 'movement', 6, true),
('Walk around my neighborhood', '🏘️', 'orange', 'movement', 7, true),
('Take a walk in nature', '🌳', 'orange', 'movement', 8, true),
('Start my day with morning stretches', '🌅', 'orange', 'movement', 9, true),
('End my day with wind down stretches', '🌙', 'orange', 'movement', 10, true),
('Do 10 shoulder rolls', '🔄', 'orange', 'movement', 11, true),
('Hold a plank for 10 seconds', '🏋️', 'orange', 'movement', 12, true),
('Do 5 jumping jacks', '⭐', 'orange', 'movement', 13, true),
('Do 5 squats', '🦵', 'orange', 'movement', 14, true),
('Do 5 wall push ups', '💪', 'orange', 'movement', 15, true),
('Do 5 sit-ups', '🔥', 'orange', 'movement', 16, true),
('Do 10 lunges', '🦿', 'orange', 'movement', 17, true),
('Pace around during a call', '📱', 'orange', 'movement', 18, true),
('Stand up once while watching TV', '📺', 'orange', 'movement', 19, true),
('Go for a short walk after my meal', '🍽️', 'orange', 'movement', 20, true);

-- Insert Self-kindness tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Do one thing that makes me happy', '😊', 'pink', 'self-kindness', 1, true),
('Name one small thing I did well today', '⭐', 'pink', 'self-kindness', 2, true),
('Give myself permission to rest', '😌', 'pink', 'self-kindness', 3, true),
('Give myself a hug', '🤗', 'pink', 'self-kindness', 4, true),
('Say one kind thing to myself as if I were a friend', '💬', 'pink', 'self-kindness', 5, true),
('Thank myself for making it through the day', '🙏', 'pink', 'self-kindness', 6, true),
('Name one thing I''m grateful to my body for', '🫀', 'pink', 'self-kindness', 7, true),
('Read a simple affirmation for myself', '📖', 'pink', 'self-kindness', 8, true),
('Name one thing I like about myself', '💕', 'pink', 'self-kindness', 9, true),
('Name one small success from today', '🏆', 'pink', 'self-kindness', 10, true),
('Give myself a small treat', '🍫', 'pink', 'self-kindness', 11, true),
('Start your day with an affirmation', '🌅', 'pink', 'self-kindness', 12, true),
('Smile at myself in the mirror', '🪞', 'pink', 'self-kindness', 13, true),
('Accept that I''m a work in progress', '🌱', 'pink', 'self-kindness', 14, true),
('Name one quality I''m developing', '💪', 'pink', 'self-kindness', 15, true),
('Embrace an imperfection as part of what makes me unique', '✨', 'pink', 'self-kindness', 16, true),
('Allow myself to feel my emotions without judgment', '💭', 'pink', 'self-kindness', 17, true),
('Say "I accept myself as I am right now"', '🙌', 'pink', 'self-kindness', 18, true),
('Replace "I should" with "I choose to"', '🔄', 'pink', 'self-kindness', 19, true),
('Tell myself "I just need to do my best" when overwhelmed', '🌊', 'pink', 'self-kindness', 20, true),
('Pause and say "thank you" to myself', '🙏', 'pink', 'self-kindness', 21, true);

-- Insert Sleep tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Get 10 min of sunlight in the morning', '☀️', 'indigo', 'sleep', 1, true),
('Go to bed at the same time every night', '🛏️', 'indigo', 'sleep', 2, true),
('Avoid caffeine after lunch', '☕', 'indigo', 'sleep', 3, true),
('Say one thing I''m grateful for before bed', '🙏', 'indigo', 'sleep', 4, true),
('Avoid heavy meals before bed', '🍽️', 'indigo', 'sleep', 5, true),
('Write down all my thoughts and worries', '📝', 'indigo', 'sleep', 6, true),
('Silence notifications before bed', '🔕', 'indigo', 'sleep', 7, true),
('Wind down with a sleep breathing exercise before bed', '😴', 'indigo', 'sleep', 8, true),
('Read something relaxing before bed', '📖', 'indigo', 'sleep', 9, true),
('Make myself a cup of chamomile tea after dinner', '🍵', 'indigo', 'sleep', 10, true),
('Dim the lights 30 minutes before bed', '💡', 'indigo', 'sleep', 11, true),
('Listen to soothing music before bed', '🎵', 'indigo', 'sleep', 12, true),
('Take a warm shower or bath before bed', '🛁', 'indigo', 'sleep', 13, true),
('Limit social media before bed', '📵', 'indigo', 'sleep', 14, true),
('Close all my curtains for darkness', '🌑', 'indigo', 'sleep', 15, true),
('Make my bed', '🛏️', 'indigo', 'sleep', 16, true),
('Listen to soft music before bed', '🎶', 'indigo', 'sleep', 17, true),
('Avoid naps longer than 30 minutes', '⏰', 'indigo', 'sleep', 18, true),
('Open my curtains first thing in the morning', '🌅', 'indigo', 'sleep', 19, true),
('Wake up at a consistent time', '⏰', 'indigo', 'sleep', 20, true),
('Eat my last meal 3 hours before bed', '🍽️', 'indigo', 'sleep', 21, true),
('Skip that drink tonight', '🚫', 'indigo', 'sleep', 22, true);

-- Insert Gratitude tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Say one thing I''m grateful for before bed', '🙏', 'yellow', 'gratitude', 1, true),
('Thank myself for making it through the day', '💪', 'yellow', 'gratitude', 2, true),
('Name one thing I''m grateful to my body for', '🫀', 'yellow', 'gratitude', 3, true),
('Compliment someone', '💬', 'yellow', 'gratitude', 4, true),
('Name one thing I appreciate about someone', '❤️', 'yellow', 'gratitude', 5, true),
('Notice a small joy in my day', '✨', 'yellow', 'gratitude', 6, true),
('Write one thing in a gratitude reflection', '📝', 'yellow', 'gratitude', 7, true),
('Name one thing that made me happy today', '😊', 'yellow', 'gratitude', 8, true),
('Say thank you to someone', '🙏', 'yellow', 'gratitude', 9, true),
('Take a moment to breathe the fresh air', '🌬️', 'yellow', 'gratitude', 10, true),
('Look at the sky and appreciate its beauty', '🌤️', 'yellow', 'gratitude', 11, true),
('Pause and appreciate the food I''m about to eat', '🍽️', 'yellow', 'gratitude', 12, true),
('Notice one thing around me that brings me peace', '🕊️', 'yellow', 'gratitude', 13, true),
('Think of someone who helped me today', '💭', 'yellow', 'gratitude', 14, true),
('Treat one everyday object like a gift', '🎁', 'yellow', 'gratitude', 15, true),
('Name one small thing I did well today', '⭐', 'yellow', 'gratitude', 16, true),
('Think about a favorite memory', '💭', 'yellow', 'gratitude', 17, true),
('Pause and say "thank you" to myself', '🙏', 'yellow', 'gratitude', 18, true),
('Think about how chores make my life better', '🧹', 'yellow', 'gratitude', 19, true),
('Appreciate how cozy my bed is before getting up', '🛏️', 'yellow', 'gratitude', 20, true),
('Express gratitude to a loved one', '❤️', 'yellow', 'gratitude', 21, true);

-- Insert Hygiene tasks
INSERT INTO task_templates (title, emoji, color, category, display_order, is_active) VALUES
('Brush teeth', '🪥', 'cyan', 'hygiene', 1, true),
('Wash my face', '🧼', 'cyan', 'hygiene', 2, true),
('Take a shower', '🚿', 'cyan', 'hygiene', 3, true),
('Floss my teeth', '🦷', 'cyan', 'hygiene', 4, true),
('Wash my hands when I get home', '🧴', 'cyan', 'hygiene', 5, true),
('Brush my hair', '💇', 'cyan', 'hygiene', 6, true),
('Wear clean clothes', '👕', 'cyan', 'hygiene', 7, true),
('Wear clean socks', '🧦', 'cyan', 'hygiene', 8, true),
('Trim my nails', '💅', 'cyan', 'hygiene', 9, true),
('Moisturize my skin', '🧴', 'cyan', 'hygiene', 10, true),
('Wash my hair', '🧴', 'cyan', 'hygiene', 11, true),
('Wipe down my phone', '📱', 'cyan', 'hygiene', 12, true),
('Disinfect my keyboard', '⌨️', 'cyan', 'hygiene', 13, true),
('Carry hand sanitizer when I go out', '🧴', 'cyan', 'hygiene', 14, true),
('Wash bathroom towels', '🧺', 'cyan', 'hygiene', 15, true),
('Clean bed sheets', '🛏️', 'cyan', 'hygiene', 16, true),
('Do laundry', '🧺', 'cyan', 'hygiene', 17, true),
('Wipe down bathroom counter', '🧽', 'cyan', 'hygiene', 18, true),
('Clean water bottle', '💧', 'cyan', 'hygiene', 19, true),
('Apply sunscreen before going outside', '☀️', 'cyan', 'hygiene', 20, true);